src/renderer/src/components/entry-column/index.tsx, src/renderer/src/components/feed-column/item.tsx, src/renderer/src/pages/(main)/(context)/index.tsx
Before:
https://github.com/RSSNext/follow/assets/41265413/461fef9d-4dd5-43cf-8e9f-1933be5a8bb4
Fixed
https://github.com/RSSNext/follow/assets/41265413/3933ece0-ad58-4322-849c-e25cfe883570
=> fix: entry refresh logic

src/renderer/src/modules/entry-column/index.tsx
The logo's in the wrong place again, fix it again!
=> fix: align logo again

eslint.config.mjs, src/renderer/src/components/ui/modal/stacked/modal.tsx, src/renderer/src/components/ui/tabs.tsx, src/renderer/src/pages/(external)/(with-layout)/feed/[id]/index.tsx, src/renderer/src/pages/(external)/login.tsx, src/renderer/src/pages/(external)/redirect.tsx, src/renderer/src/pages/add/index.tsx, src/renderer/src/pages/preview.tsx, src/renderer/src/router.tsx, src/shared/src/electron.ts
Add eslint rule:
```
Since you don't use the same router instance in electron and browser, you can't use the global location to get the route info. \n\n" + "You can use `useLocaltion` or `getReadonlyRoute` to get the route info.
```
=> fix: ban global `location`

src/main/tipc.ts, src/renderer/src/atoms/route.ts, src/renderer/src/components/common/LoadRemixAsyncComponent.tsx, src/renderer/src/components/ui/modal/stacked/hooks.tsx, src/renderer/src/components/ui/modal/stacked/modal.tsx, src/renderer/src/components/ui/select.tsx, src/renderer/src/lib/enum.ts, src/renderer/src/modules/feed-column/category.tsx, src/renderer/src/modules/feed-column/index.tsx, src/renderer/src/modules/feed-column/item.tsx, src/renderer/src/modules/feed-column/list.tsx, src/renderer/src/modules/settings/modal/content.tsx, src/renderer/src/modules/settings/modal/context.tsx, src/renderer/src/modules/settings/modal/hooks.ts, src/renderer/src/modules/settings/modal/layout.tsx, src/renderer/src/modules/settings/tabs/apperance.tsx, src/renderer/src/providers/biz-router-provider.tsx, src/renderer/src/providers/root-providers.tsx, src/renderer/src/providers/ui-setting-Initialize.tsx, src/renderer/src/store/ui.ts, src/renderer/src/store/unread.ts, src/renderer/src/store/utils/helper.ts
- Setting modal only can present once if exists.
- Vite hmr will lost state in setting modal
- Keep page params if reload page
=> feat: macos docker badge and unread count setting

src/renderer/src/modules/settings/setting-builder.tsx
Currently, you can not enter the appearance section in web settings.
I also hide the unavailable setting group.
=> fix(web): can not enter settings, hide disabled title

package.json, pnpm-lock.yaml, src/main/tipc.ts, src/renderer/src/App.tsx, src/renderer/src/components/ui/background/vibrancy.tsx, src/renderer/src/components/ui/code-highlighter/shiki/hooks.ts, src/renderer/src/components/ui/sonner.tsx, src/renderer/src/hooks/common/useDark.ts, src/renderer/src/modules/settings/tabs/apperance.tsx, src/renderer/src/providers/root-providers.tsx, src/renderer/src/providers/ui-setting-sync.tsx
Set app theme via `nativeTheme.themeSource` instead of renderer scope dark
=> fix: set app dark mode instead of renderer

src/renderer/src/initialize/hydrate.ts, src/renderer/src/lib/utils.ts, src/renderer/src/modules/entry-column/hooks.ts, src/renderer/src/store/entry/store.ts
When the query for the entry list is refreshed, retain the read entries that have already been rendered in the unread list.
=> feat: dont shink unread when query refreshed

icons/mgc/eye_2_cute_re.svg, src/renderer/src/modules/entry-content/index.tsx
For this feature, optimistic update rendering is executed within the UI layer rather than the queries layer due to the utilization of the read data mutation in certain instances via react query and in others through the patch method within the data store. This disparity significantly complicates the endeavor of maintaining data consistency. It may be necessary to address this issue at a later time.
The original approach undertaken was outlined as follows for renference:
=> feat: read count

src/renderer/src/pages/(external)/redirect.tsx
before             |  after
:-------------------------:|:-------------------------:
=> fix: improve responsiveness

src/renderer/src/constants/tabs.tsx, src/renderer/src/database/db.ts, src/renderer/src/database/db_schema.ts, src/renderer/src/modules/feed-column/category.tsx, src/renderer/src/modules/feed-column/index.tsx, src/renderer/src/services/entry.ts, src/renderer/src/services/subscription.ts, src/renderer/src/store/entry/store.ts, src/renderer/src/store/subscription/hooks.ts, src/renderer/src/store/subscription/store.ts
https://github.com/user-attachments/assets/adba5f22-7599-46aa-9a98-5757d26b14d1
=> feat: change folder to other view

src/renderer/src/components/ui/markdown/renderers/BlockImage.tsx
In other APP
Before
After
This shouldn't affect the image styling of other entries?
=> fix: inline image style

src/renderer/src/modules/settings/tabs/about.tsx
=> chore: update external link style in about settings tab

src/renderer/src/components/ui/radio-group/Radio.tsx, src/renderer/src/components/ui/radio-group/RadioCard.tsx, src/renderer/src/components/ui/radio-group/RadioGroup.tsx, src/renderer/src/components/ui/radio-group/context.ts
This pull request fixes an issue where the radio label was not behaving correctly when clicked.
The issue was caused by incorrect usage of the `id` and `htmlFor` attribute in the `Radio` components.
This PR updates components to use the `useId` within `Radio` and respect the ID input by the user.
Before
https://github.com/user-attachments/assets/1c942d5c-a0e3-46ff-8081-d1deeba35704
After
https://github.com/user-attachments/assets/90d02eca-8a08-4908-9075-ceb8177c1953
=> fix: incorrectly behavior when click radio label

src/renderer/src/components/ui/button/index.tsx, src/renderer/src/modules/settings/tabs/about.tsx
This pr uses `asChid` to remove unsafe ts-expect-error directive in the about page.
This pull request also fixes errors when using `asChild` in the button component.
```
Error: React.Children.only expected to receive a single React element child.
```
The loading function also works normally.
Refer to https://github.com/shadcn-ui/ui/issues/3117
=> fix: button component with asChild

src/renderer/src/modules/entry-content/header.tsx
`text-lg` can affect `line-height`, causing avatar groups to be too close to the top
reset it with `leading-none`
Before: 
After:
=> style: reset the EntryReadHistory line-height

.github/workflows/build.yml, package.json
Make build work for Intel-based Mac.
Note: The introduced `build:macos` script requires OSX signing and won't function without it. Refer to https://github.com/electron/forge/issues/3271 for details. **I was not able to create a test build due to this issue.** I would appreciate it if the maintainers could assist in testing this before merging. This shouldn't be a problem on GH Action as signing is properly configured.
=> build: making universal build for macOS

src/renderer/src/components/feed-icon.tsx
Search Link: 
https://www.developerway.com/rss.xml
Before:
After:
=> fix: fix style when image and name both empty

src/renderer/src/lib/url-to-iframe.ts
This pull request fixes the issue where the embed player will check `window.REFERRER_LIST` by `PlayerUtil.isCertifiedReferrer()` and throw `[Permission] Not Allowed` error.
=> fix: use official embed player in bilibili video when use web

.github/workflows/build.yml, .github/workflows/tag.yml, package.json, pnpm-lock.yaml
To make the release version easy.
https://github.com/orgs/RSSNext/projects/1?query=sort%3Aupdated-desc+is%3Aopen&pane=issue&itemId=73154264
Better to do:
- run `npm run bump` in local.
- then merge release pr in the pull request.
- CI run and release version as Pre-release.
=> ci: add bump release workflow

src/renderer/src/modules/discover/feed-form.tsx, src/renderer/src/modules/profile/user-profile-modal.tsx
Fixed the issue where subscription was active, but still showed as unsubscribed in the Profile.
Before:
After:
And fixed the warning of the input component when the Category is null
Befor:
=> fix: subcription status & input component warning

src/renderer/src/pages/settings/(settings)/profile.tsx
1. After modifying the profile, switching to the settings tab will display the old data before the modification.
2. The submit button is missing a load animation
Before:
https://github.com/user-attachments/assets/e5aaa80c-0d73-4f26-a7c8-3d2c11e3d0e0
After:
https://github.com/user-attachments/assets/64f1e01c-9797-47a1-921a-41e830920cce
=> fix: profile fields are not updated after modifying the profile

src/renderer/src/modules/entry-column/templates/list-item-template.tsx
Make readed article title into gray.
**Before: title will not be gray after read**
**After: title wil be gray after read**
=> UI Improvement: make readed article color into gray

src/renderer/src/modules/settings/tabs/about.tsx
Add whitespace before LICENSE in about page
|before|after|
|:--:|:--:|
|![image](https://github.com/user-attachments/assets/55939960-6d2a-43d2-86e3-2535cfcd5e1b)|![image](https://github.com/user-attachments/assets/42ce900c-27e5-4181-9740-4b6498d99166)|
=> chore: add whitespace before license in about page

src/renderer/src/modules/discover/form.tsx
This PR enhances the search functionality by sorting the returned results based on the number of followers when searching for a keyword or an address across multiple feeds.
When searching for keywords and encountering multiple subscription sources, it can be difficult to determine which one to subscribe to. Typically, the feed with the highest number of followers is more likely to be reliable. This update helps users make better decisions by prioritizing results with more followers.
=> feat: sort the query results by the number of followers in asc order

src/renderer/src/modules/entry-content/components/EntryReadHistory.tsx
This PR fixes the incorrect usage in the tooltip in the read history.
Before
After
=> fix: incorrect tooltip in read history

src/renderer/src/modules/discover/feed-form.tsx, src/renderer/src/queries/subscriptions.ts
When editing the feed's category, the suggestion list only shows the categories from the current feed's view. If you want to use category names from other views, you have to re-enter them. This PR is intended to display categories from all views in the suggestions
#391 
before:
after:
=> feat: prompt the full categories when editing the feed

locales/external/zh-CN.json
This PR adds the `zh-CN` translation for the external page to make zh-cn 100% translated.
=> feat(i18n): add zh-CN i18n for external page

src/renderer/src/modules/entry-content/components/EntryReadHistory.tsx
it is a bug from https://github.com/RSSNext/Follow/pull/377
it should be open when the mouse hover, but it always show now.
=> fix: read history always show

apps/renderer/src/modules/settings/sections/fonts.tsx
The default selected value of Content Font is empty.
Only on the Follow app.
/
=> fix: empty default font on electron app

apps/renderer/src/components/feed-icon.tsx, apps/renderer/src/components/ui/platform-icon/index.tsx
I was importing github releases but it crashed the discover page
It seems the issue is caused by the `docs` type item.
This PR makes it compatible with the `docs` type item.
=> fix: crashes when docs appear in the discover result

apps/renderer/src/modules/panel/cmdk.tsx
I found that in the search results of the search panel, if there are duplicate items (possibly because an RSS author deleted and then republished an article), it causes abnormal hover styles with the mouse.
I changed the value of the key to make it less likely to repeat, in order to avoid this situation.
https://github.com/user-attachments/assets/69453c9e-2b3f-4f36-8ed4-513bb3c9cf9c
=> fix: ensure unique keys for search items

apps/renderer/src/modules/discover/DiscoverFeedForm.tsx
use `<Markdown />` to render rsshub route desc link preview
=> fix: should use markdown to render link in rsshub parameter desc

apps/renderer/src/modules/entry-column/templates/list-item-template.tsx
1. fix estimatedMins style can see in   https://meanc.cc/backdrop-blur-dao-zhi-yuan-jiao-ju-chi
2. adjust animation with the button
https://github.com/user-attachments/assets/9662092f-761c-4055-b3d1-0cec12ea8247
=> fix: audioCover animation and estimatedMins style

apps/renderer/src/modules/feed-column/corner-player.tsx
1. Adjust the animation for displaying podcast names and times
2. Increase slider size and mouse style when hovering
3. Adjust the operation bar, with project operations on the left and audio operations on the right
4. Abstracting the function for obtaining time display text into usecallback
=> feat: change corner-player animation

apps/renderer/src/components/ui/media/preview-media.tsx
Fix the position of navigation buttons in media swiper.
None
None
=> fix: position of swiper navigation buttons

apps/renderer/src/lib/color.ts, apps/renderer/src/styles/colors.css, tailwind.config.ts
Follow mixes modern HSL syntax with legacy syntax. This can result in invalid values like `hsl(h, s, l / alpha)` or `hsl(h s l, alpha)` when using CSS variables and the Tailwind theme.
This PR deprecates all hsl legacy syntax from the codebase.
https://github.com/user-attachments/assets/0766ad2f-4f66-432a-a7a1-616c25938355
=> refactor: deprecate hsl legacy syntax

apps/renderer/src/@types/constants.ts
This PR removes the duplicated English language and adjusts the sorting of the supported languages for better organization.
Before
After
=> fix: remove duplicated en and tweak lang sort

apps/main/src/lib/proxy.ts
Blame to https://github.com/RSSNext/Follow/pull/452
This PR introduces the ability to cancel the proxy configuration when user input empty string.
=> fix: allow cancel proxy configuration

apps/renderer/src/modules/panel/cmdk.tsx
This PR complements #500. Thanks to @lainbo for bringing this issue to my attention during testing, giving me the opportunity to further refine the bug fix.
Closes #500
Refer to [cmdk Item [cmdk-item] [data-disabled?] [data-selected?]](https://github.com/pacocoursey/cmdk#item-cmdk-item-data-disabled-data-selected) documentation.
Based on the [cmdk source code](https://github.com/pacocoursey/cmdk/blob/main/cmdk/src/index.tsx#L47-L52), we removed the invalid prop `id` from `Command.Item`.
Thanks to the development team for their code review.
<details>
<summary>Test Information</summary>
For testing purposes, you can use this feed: https://deer404.com/feed.xml
</details>
=> fix: search items ensure unique keys

apps/renderer/src/modules/entry-column/translation.tsx
prevent translation popup from being obscured by time display
#625
=> fix: prevent translation popup from being obscured by time display

apps/renderer/src/components/ui/media.tsx, apps/renderer/src/components/ui/media/VideoPlayer.tsx, apps/renderer/src/modules/entry-column/templates/list-item-template.tsx
When the preview video is loaded for the first time, the mute icon flashes and misplaces
before:
https://github.com/user-attachments/assets/f80d9a36-084f-416e-a712-abb8689f04b8
after: 
https://github.com/user-attachments/assets/52f4d81b-1f15-46cf-b396-3a69f4414503
=> style: fix the FloatMutedButton mispositioning

apps/renderer/src/components/ui/media.tsx
display white block if can't fetch preview video, so i add poster to video attribute
#554 
https://github.com/user-attachments/assets/b60f32a1-e899-4427-a9da-c5bbcbcc0b5e
[fixed.webm](https://github.com/user-attachments/assets/b18d00c6-36ff-4980-9493-a98411aab73b)
=> fix: display white block if can't fetch preview video

apps/renderer/src/constants/shortcuts.ts, apps/renderer/src/global.d.ts, apps/renderer/src/modules/modal/shortcuts.tsx, apps/renderer/src/pages/(external)/(with-layout)/feed/[id]/index.tsx, apps/renderer/src/pages/settings/(settings)/shortcuts.tsx, locales/external/en.json, locales/external/zh-CN.json, locales/external/zh-HK.json, locales/external/zh-TW.json, locales/shortcuts/en.json, locales/shortcuts/zh-CN.json, locales/shortcuts/zh-HK.json, locales/shortcuts/zh-TW.json
=> feat: add some i18n

apps/renderer/src/components/ui/datetime/index.tsx
修改列表時間標題的Tooltip内容，目前會顯示年月日和時間，但是時間永遠是 23：59
這個是一個 '天’ 的概念，我覺得只顯示年月日就行
---
Modify the Tooltip content of the list date headers. Currently, it shows the date and time, but the time is always 23:59. Since this represents a 'day' concept, I think showing just the date is sufficient.
=> fix: modify the Tooltip content of the list dates title

apps/renderer/src/modules/profile/user-profile-modal.tsx
When scrolling through the user interface, the styles of user titles switch abruptly. Perhaps we can make the transition smoother.
**Old**
**New**
=> feat(user-profile): smoother height switching

apps/renderer/src/components/ui/modal/stacked/hooks.tsx, apps/renderer/src/modules/modal/shortcuts.tsx
Using `H` to open shortcut mode, pressing `H` again cannot close it
=> fix: ShortcutMode cannot be closed using shortcuts keys

apps/renderer/src/modules/feed-column/category.tsx, apps/renderer/src/store/subscription/store.ts
https://github.com/RSSNext/Follow/pull/709#issuecomment-2382464274
A little later I'll look into whether there should be a better way to initialize the feed data for the default categories
@hyoban
=> fix: wrong opening status of newly added feed

apps/renderer/src/modules/entry-column/item.tsx, apps/renderer/src/modules/entry-column/layouts/EntryItemWrapper.tsx
In the grid browsing mode of images and on the video content display page, when the mouse hovers over an image, the shadow is not fully displayed and appears truncated at the top.
I identified that the issue was caused by the "inset-y-1" style in the 「ListItemHoverOverlay」 component.
As this is a foundational component, I opted not to modify it directly. Instead, I introduced an "overlayItemClassName" attribute to the 「EntryItemWrapper」 component to address the style issue.
I had previously submitted a PR. Upon discovering that the manager had refactored the component I modified, so I closed the PR, made further adjustments, and resubmitted it.
previous PR:  https://github.com/RSSNext/Follow/pull/710
=> fix: grid mode for images and video content page, shadow not fully displayed when the mouse hovers over

apps/renderer/src/components/ui/modal/stacked/modal.tsx
This PR modifies the modal title component to truncate long titles, ensuring that they fit within the available space.
This change enhances the user interface by preventing overflow and maintaining a clean layout.
Before
After
=> fix: truncate long title in dialog title

apps/renderer/src/modules/settings/modal/layout.tsx
Fix two problems：
When the modal is moved
1、The content inside becomes blurred 
2、The button prompts are not displayed fully
https://github.com/user-attachments/assets/83dcfa68-2d49-4167-aedf-1ef6bc9b1763
=> fix: resolve content blur after modal dragged

apps/renderer/src/modules/entry-column/Items/social-media-item.tsx
在社交媒体列表滚动时，能感知到骨架屏样式和卡片样式不一致。此 PR 为了对齐两者样式。
之前：
之后：
=> fix(styles): align the styles of SocialMediaItem and Skeleton

apps/renderer/src/components/header.tsx, apps/renderer/src/components/ui/markdown/renderers/MarkdownLink.tsx
`/profile/xxx` 和 `/feed/xxx` 路由下的 header 在 1024~1280px 的页面宽度下显示有点异常，看不到圆角和外边距：
可以在这里验证问题：https://app.follow.is/feed/41223694984583170
修复后：
=> fix: external layout header margin

apps/renderer/src/components/ui/code-highlighter/copy-button.tsx, apps/renderer/src/lib/error-parser.ts, apps/renderer/src/modules/discover/inbox-form.tsx, apps/renderer/src/modules/discover/inbox-list-form.tsx, apps/renderer/src/modules/feed-column/index.tsx, apps/renderer/src/modules/settings/tabs/lists.tsx, apps/renderer/src/providers/root-providers.tsx
This PR introduces:
1. Move all use of `toast.error` on react-query's `onError` to use `toastFetchError`
1. UI optimization for error toast
| |Before | After |
| --- |--- | --- |
| 1 | ![Screenshot 2024-10-05 at 20 57 33](https://github.com/user-attachments/assets/fd1890a5-e8c8-4d28-8a66-ad7613efe3a2) | <img width="404" alt="Screenshot 2024-10-05 at 20 57 25" src="https://github.com/user-attachments/assets/0f683f53-2577-4618-8cd3-2d8394f1e8f4"> | 
| 2 |<img width="439" alt="Screenshot 2024-10-05 at 20 48 30" src="https://github.com/user-attachments/assets/69ff64b6-a8fa-4034-a88c-5ad4740bf57b"> | <img width="426" alt="Screenshot 2024-10-05 at 20 54 57" src="https://github.com/user-attachments/assets/736c7e3d-3360-4d0c-96a7-76485675164c"> |
=> refactor: optimize ui of error toast

apps/renderer/src/components/ui/modal/stacked/helper.tsx, apps/renderer/src/components/ui/modal/stacked/modal.tsx, apps/renderer/src/modules/settings/modal/layout.tsx
https://github.com/RSSNext/Follow/blob/5285ea4ad97cbf86a171d2c273d159d0e89fb7eb/apps/renderer/src/modules/settings/modal/layout.tsx?plain=1#L97-L99
If I don't get it wrong, these lines mean enable `bottomRight` only.
But as bokuweb/re-resizable said,
> If you want to permit only right direction resizing, set `{ top:false, right:true, bottom:false, left:false, topRight:false, bottomRight:false, bottomLeft:false, topLeft:false }`.
This PR makes `<Resizable>` enables `bottomRight` only.
=> fix: setting modal should be resizable from bottomRight only

apps/renderer/src/components/ui/modal/stacked/hooks.tsx, apps/renderer/src/components/ui/modal/stacked/modal.tsx, apps/renderer/src/modules/settings/modal/layout.tsx
Resizing is not that natural now.
For example, when we move the top handle, the box becomes shorter from bottom.
https://github.com/user-attachments/assets/bda13586-200b-4809-a070-3ea179bf91a7
This PR combines `resizing` and `dragging` when the user is `resizing` from `top` or `left` to make sure the box is resizing following the cursor. Screencast:
https://github.com/user-attachments/assets/4d9c15b9-52c0-46e6-a9c7-918d5a9dd9e1
=> refactor: make resizing more natural

README.md, apps/main/src/init.ts
Currently, it is very inconvenient to develop with Electron on windows:
When developers run `pnpm run dev` in terminal, an electron instance will be started.
Then it alerts developer to login. After logging in in the opened browser, we are required to open `follow-dev://auth?token=xxx` in the browser to continue.
That's the problem. A separate electron instance will be started instead of using the already running one.
For the second instance, it does not have the environment variable needed to launch (including ELECTRON_RENDERER_URL and those in .env), which is loaded by the first instance but not passed to the second instance.
The essential question we need to address is why the second instance was initiated (why requestSingleInstanceLock not work).
So that's why. The second instance is …
=> fix: improve developing experience with Electron on Windows

apps/main/package.json, apps/main/src/lib/proxy.test.ts, apps/main/src/lib/proxy.ts, apps/main/vitest.config.ts, package.json
Fix https://github.com/RSSNext/Follow/issues/807. This pull request enhances the handling of proxy URIs by ensuring that only the first proxy is used when multiple URLs are provided.
Additionally, it introduces unit tests for the proxy configuration, validating both valid and invalid proxy inputs, as well as the behavior of the proxy update function. The Vitest setup has also been updated to facilitate testing.
=> fix: improve proxy URI handling

apps/main/src/index.ts
`browser-window-created` should be listened before calling `new BrowserWindow()`. Close #832 
#832
=> fix: F12 cannot open devTools in development mode

apps/main/src/window.ts
Change the default font-family and font-size of the devtools. Make it consistent with Chrome on Windows, instead of SimSun.
ref: [[Feature Request]: Add possibility to change DevTools font · Issue #42055 · electron/electron](https://github.com/electron/electron/issues/42055)
=> chore: improve devtools font on Windows

apps/renderer/src/components/ui/modal/stacked/overlay.tsx
close #838
The reason for this is that when multiple modals were being displayed off-rotation, the old modal had pointer-events-none set so that clicks were not blocked.
=> fix: Mouse click may briefly overlap with background elements

apps/renderer/src/modules/entry-content/components/EntryReadHistory.tsx
The previous use of reletive & right resulted in the actual width of the element covering the button, causing it to be unclickable     
#843
=> fix: avatar element masking button

apps/renderer/src/modules/trending/index.tsx, apps/renderer/src/pages/(main)/(layer)/(subview)/discover/index.tsx
discover page's trending icon is offset.
https://github.com/user-attachments/assets/e31ecd0a-c543-4668-997d-62634613a11b
=> fix: discover page's trending icon is offset.

apps/renderer/src/modules/discover/DiscoverFeedForm.tsx, apps/renderer/src/modules/discover/transform-form.tsx, apps/renderer/src/pages/(main)/(layer)/(subview)/discover/index.tsx, locales/app/en.json
https://github.com/user-attachments/assets/0512c7da-a36d-42d9-b27b-6572c6f3df76
- close #618
- <del> wait for https://github.com/DIYgod/RSSHub/pull/17081 </del>
- related #808
=> feat: transform html

apps/renderer/src/components/ui/context-menu/context-menu.tsx, apps/renderer/src/components/ui/modal/stacked/declarative-modal.tsx, apps/renderer/src/components/ui/modal/stacked/modal.tsx, apps/renderer/src/components/ui/modal/stacked/overlay.tsx, apps/renderer/src/components/ui/modal/stacked/provider.tsx, apps/renderer/src/components/ui/select.tsx, apps/renderer/src/modules/panel/cmdf.tsx, apps/renderer/src/pages/(main)/layout.tsx, apps/renderer/src/providers/app-grid-layout-container-provider.tsx, apps/renderer/src/providers/root-providers.tsx
This pull request revamps the z-index usage across the application, simplifying the modal structure and overlay handling.
Unnecessary z-index values have been removed from components, leading to a cleaner and more maintainable codebase.
But this pull request breaks some cases in the modal overlay and may not meet all business scenarios. 
Related to https://github.com/RSSNext/Follow/pull/859
See also [Stop (ab)using z-index](https://www.codegram.com/blog/stop-ab-using-z-index/)
=> refactor: revamp z-index usage

apps/renderer/src/modules/entry-column/components/mark-all-button.tsx
The height of the one-click read flag ui on the window web is not correct.
Should be judged to be enabled only in clients on Win `-ElECTRON_CUSTOM_TITLEBAR_HEIGHT`
=> fix: windows web mark all read ui

apps/renderer/src/modules/profile/user-profile-modal.tsx
before:
https://github.com/user-attachments/assets/c84c2547-0f10-4fb2-9b3a-79834fd8cd70
after:
https://github.com/user-attachments/assets/ac708d33-d1a1-4d06-808f-57fb9b3aabc3
=> feat(profile): add transition effects to user avatar display

apps/renderer/src/modules/entry-column/components/mark-all-button.tsx
fix https://github.com/RSSNext/Follow/issues/958#issuecomment-2415633588 
The fix now is to use useViewport to get the component to re-render, and I'm not sure that's appropriate
=> fix: Fix popup's width when viewport changes.

apps/main/src/lib/router.ts
fix: Fixed the issue where the URL parser automatically normalized the path /add to /add/, preventing the add operation from being triggered correctly.
close #949
=> fix: deeplink adding feed does not work on Windows

apps/renderer/src/modules/feed-column/category.tsx
A requirement in #941 to expand and collapse categories by double clicking on their names
=> feat: expand collapse category  by double-clicking

apps/renderer/src/pages/(main)/(layer)/(subview)/layout.tsx
Fix electron window layout titleSticky ui
Before
After
https://github.com/RSSNext/Follow/issues/958#issue-2588461487
=> fix: electron window layout titleSticky ui

apps/renderer/src/store/feed/store.ts, apps/renderer/src/store/image/index.ts
=> refactor: tidy up

apps/renderer/src/modules/entry-content/index.tsx
When the container size is lower than 700px, the toc cannot be displayed in full.
Now:
=> fix(toc): When not displayed at small sizes

apps/renderer/src/modules/claim/hooks.ts, apps/renderer/src/modules/entry-content/components/EntryReadHistory.tsx
- Fix the bug that the close button of the authentication feed popup ui on authenticationwin is blocked by the top bar.
Before
After
- Adjust the number of reading history avatars displayed on narrow screens
Before
After
I've adjusted a more comfortable spacing on win here, if it's not right on mac you can look at mac and then return the parameters based on the platform 
https://github.com/RSSNext/Follow/issues/958#issue-2588461487
=> fix: win UI - feed claim modal ui &  header readHistory ui

apps/renderer/src/pages/(main)/(layer)/(subview)/discover/index.tsx
1. Discover Page' Trending Icon margin right too narrow
2. in Discover Page, content of Search, RSS, RSSHub, RSS3, User, Transform, Import are not centered
**before**
**after**
=> fix: optimize the content margin of the Discover Page

apps/renderer/src/modules/discover/form.tsx
This PR fixes the issue that '0' is not shown when there's no followers on the search results card.
=> fix: not showing '0' when no followers on the search results card

apps/renderer/src/pages/(main)/(layer)/(subview)/discover/index.tsx
the search results on the Discover Page are not centered
**before**
**after**
=> fix: the search results on the Discover Page are not centered

apps/main/src/window.ts
- Adjust window position calculation to consider taskbar location
- Modify window size calculation to respect taskbar dimensions
- Ensure window stays within visible screen bounds
- Use workArea instead of screenSize for more accurate measurements
- Implement dynamic minimum window size based on available screen space
=> fix: improve window positioning and sizing to account for taskbar

apps/renderer/src/modules/entry-column/layouts/EntryListHeader.tsx, locales/app/en.json
=> fix: add height to EntryListHeader for consistent layout

apps/renderer/src/modules/entry-column/layouts/EntryListHeader.tsx
This issue https://github.com/RSSNext/Follow/issues/1049 mentions the problem of the top bar being obscured. 
This PR https://github.com/RSSNext/Follow/pull/1051 addresses that issue.
But I noticed there are still some problems on the Video page.
The margins are too narrow. 
Here's how it looked before.
I tried to find the cause of the above issue. I checked the commit history, and in this commit https://github.com/RSSNext/Follow/commit/847c317bb4fe4258b7eed240e5e6422bf273838d#diff-8edd1371c19527656614803122cca80cb2fde924536821a4f868bbf727a55157, the "mb-2" style was removed, which led to the issue with the top bar being obscured. I think the removal of "mb-2" here,  is to handle the situation where there need a TimelineTabs component.
I think the approach to solving this issue should be …
=> fix: margin between the top bar and the content

apps/renderer/src/lib/api-fetch.ts
This PR introduces a feature that allows the activation modal to be closed by the user.
The `canClose` property has been added to enhance user experience by providing more control over the modal's visibility.
Before
After
=> fix: allow activation modal to be closable

apps/renderer/src/components/ui/tabs.tsx
https://github.com/user-attachments/assets/5887f22c-e0f4-4d0f-b465-7fbebfe71dae
Currently, under the power page, the tab indicator animation at the bottom will be shifted from its initial position after the page is scrolled, this can be avoided by setting style={{originY: ‘0px’,}}
This is solved by setting style={{originY: ‘0px’,}}
https://github.com/user-attachments/assets/1b95c099-54c5-4496-aa48-dda78804eb5b
=> fix: Wrong initial position of tab animation

apps/renderer/src/modules/entry-column/layouts/EntryListHeader.tsx
Related: #1054
It seems only `Pictures` doesn't need add margin style.
| before | after |
| ------- | ------ |
| <img width="450" alt="image" src="https://github.com/user-attachments/assets/981b692a-f0b4-45a8-bbec-e8cf82b2e6e9"> | <img width="470" alt="image" src="https://github.com/user-attachments/assets/e1438854-56f7-4c7d-9dfa-6c407f8c0e1e"> |
=> fix: margin condition in EntryListHeader

apps/renderer/src/modules/ai/ai-daily/daily.tsx
Daily summary feature, when long address information appears, an unfriendly horizontal scroll bar will appear. Optimize it.
=> fix: optimize the appearing horizontal scroll bar.

apps/renderer/src/modules/wallet/tip-modal.tsx
when user change the tip amount after user click "tip now". the toast is last select not correct. so I disable the amount select after click "tip now"
user select amount 10 and click tip now and select amount 20. the toast is 20 not 10
=> fix: fix toast wrong tip amount

apps/renderer/src/modules/power/transaction-section/index.tsx
Enhance the balance renderer to display the tax amount alongside the transaction amount, providing clearer financial information to users.
=> feat: display tax amount in balance renderer

apps/main/src/index.ts
Once the window is destroyed, none of the window's methods can be used (except for `destroy` and `isDestroyed`).
Fix: #1127 #1092
The reason that destroy can be called multiple times is that Electron performs a check: https://github.com/electron/electron/blob/57920e7747f09627f99ed5c27457339aa7c3fe57/shell/common/gin_helper/destroyable.cc#L28
The ability to call isDestroyed is because no window methods are used during the implementation process: https://github.com/electron/electron/blob/57920e7747f09627f99ed5c27457339aa7c3fe57/shell/common/gin_helper/destroyable.cc#L48-L49
=> fix(app): throw error popup when close window

apps/renderer/src/modules/profile/user-profile-modal.tsx, apps/server/client/pages/share/users/[id]/index.tsx, locales/common/en.json
Adding a follow user button and user ID in profile model and share page.
I see that there are routes for follow on RSSHub to follow [follow-user-subscriptions](https://docs.rsshub.app/routes/social-media#user-subscriptions) based on this.
The profile modal was tested on my Win client and web with no problem, the profile page of the share page  was not tested because I couldn't run the server (eg: https://app.follow.is/share/users/hyoban), it needs to be reviewed.
https://github.com/RSSNext/Follow/issues/480
=> feat: add follow user button in profile modal

apps/main/preload/index.ts, apps/main/src/env.ts
There is a problem with the current [isWindows11](https://github.com/RSSNext/Follow/blob/dev/apps/main/preload/index.ts#L12) detecting because `os.version()` only returns the version number and does not return the `"Windows 11"` identification before the version number.
=> fix: detecting windows11

apps/renderer/src/components/ui/modal/stacked/components.tsx
This PR fixes the issue that the close button of the settings modal overlaps the language select content.
A screenshot of this issue (web app):
=> fix: modal close button overlaps the select content

apps/renderer/src/modules/boost/boosting-contributors.tsx, apps/renderer/src/modules/entry-content/components/SupportCreator.tsx, apps/renderer/src/modules/user/UserGallery.tsx, apps/renderer/src/modules/user/utils.ts, apps/renderer/src/store/feed/store.ts
Introduce the UserGallery component to display deduplicated supporters and boosting contributors.
Refactor SupportCreator to utilize the new UserGallery for improved user presentation.
=> refactor: add UserGallery and integrate into SupportCreator

apps/renderer/src/components/ui/modal/stacked/modal.tsx
fix electron app
> I don't know why it can't be reproduced stably
- accidentally called `onClose` once more when opening the modal.
- `onClose` multiple called
https://github.com/user-attachments/assets/c3b9051f-86e7-4129-80ce-f57b67fea929
=> fix: disable `pointerDownOutside` trigger `onDismiss`

packages/utils/src/link-parser.ts
Fixed the incorrect icon reference issue. The previous code mistakenly used the [Gcore](https://gcore.com/) icon as the [Gcores](https://www.gcores.com/) icon, but these are two different websites. 
This PR corrects that mistake.
None
| Before   | After     |
| --------- | -------- |
|![before](https://github.com/user-attachments/assets/c314613c-1e92-47a2-9771-86226e21af22)| ![after](https://github.com/user-attachments/assets/4096fad5-ca79-4598-8a44-0c37fc892b1e)|
=> fix: remove gcore icon

apps/renderer/src/modules/feed/feed-title.tsx
fix: preferred title not working in entry column
before
after
=> fix: preferred title not working in entry column

apps/renderer/package.json, apps/renderer/src/lib/parse-html.ts, locales/app/ja.json, pnpm-lock.yaml
Added the mdast-util-gfm-table extension to fix a serialization error encountered when converting HTML containing table nodes to Markdown.
=> fix: html table to markdown error

apps/main/src/tipc/menu.ts, apps/renderer/src/atoms/context-menu.ts, apps/renderer/src/hooks/biz/useFeedActions.tsx, apps/renderer/src/lib/native-menu.ts, apps/renderer/src/modules/entry-column/layouts/EntryItemWrapper.tsx, apps/renderer/src/modules/feed-column/category.tsx, apps/renderer/src/modules/feed-column/item.tsx, apps/renderer/src/providers/context-menu-provider.tsx, vite.config.ts
Introduce new context menu functionality while simplifying the existing native menu structure.
Update naming conventions and replace native menu calls with context menu hooks for improved consistency and maintainability.
This pr improves the context menu by:
- Split native menu and web menu
- Move the web menu out of the `native-menu.ts`
- Return a promise within the `showContextMenu` fn.
- Sunset uses `useAnyPointDown` to keep track of the menu's state.
=> refactor: context menu functionality

apps/main/src/lib/proxy.test.ts, apps/main/src/lib/proxy.ts
Fix https://github.com/RSSNext/Follow/issues/1197
Handling default port in proxy configuration
=> fix: handling default port in proxy configuration

apps/renderer/src/modules/feed-column/item.tsx
This PR fixes the issue that feed certification icon not being shown on the sidebar due to the missing `ownerUserId` and `owner` fields.
=> fix: not showing feed certification icon on the sidebar

apps/renderer/src/modules/upgrade/container.tsx
The link in the bottom right corner where the toast pops up the first time you open it is the wrong link. "https://github.com/RSSNext/Follow/releases/tag/v0.1.2-beta.0", and it goes to “https://github.com/RSSNext/Follow/releases/tag/0.1.2-beta.0” which is a 404 error.
=> fix: app upgraded toast href error

apps/renderer/src/modules/entry-column/EntryColumnShortcutHandler.tsx, changelog/next.md
While using up and down arrow to switch between feed entries, the web will scroll a little. 
https://github.com/user-attachments/assets/a38dfba3-eeed-4213-bb63-32607247b33c
By preventing the default scrolling behavior of the arrow key, we avoid it. 
https://github.com/user-attachments/assets/2144e6f1-4a88-4018-89e3-61727b4923fe
=> fix: prevent default scrolling behavior while using arrow keys to switch between entries

apps/renderer/src/modules/power/my-wallet-section/claim-daily-reward.tsx
I wonder if it is better to remove the amount here. And actually `DAILY_CLAIM_AMOUNT.normal` isn't the real count I get today.
Before:
After:
=> fix: update daily claim amount reference in tooltip

apps/renderer/src/modules/achievement/AchievementModalContent.tsx, apps/renderer/src/modules/boost/level-benefits.tsx, locales/app/en.json, locales/app/zh-CN.json
Introduce a new achievement for boosting the feed, along with its localization in English and Chinese.
Related to https://github.com/RSSNext/follow-server/pull/170
=> feat: add feed booster achievement with localization

apps/renderer/src/modules/discover/recommendations.tsx, apps/renderer/src/queries/discover.ts, changelog/next.md
add all language filter in discover and zh-CN, zh-HK, zh-TW users should retrieve all.
=> feat: add all language filter in discover

apps/main/src/lib/cleaner.ts
The Electron assigns the latin string "Yes" to the "Confirmation" action and "No" to the "Cancel" action. Although the display order of the buttons is reversed in the English UI, the value responded when pressing the ESC key is correct (index value of the "No" button). However, in the translated UI, the default value responded when pressing the ESC key is 0 (if the correct value is not assigned to `cancelId`), which leads to the data being cleared after pressing the ESC key.
Therefore, explicitly assign a value to `cancelId`.
=> fix: explicitly assign a value to `cancelId` for ‘Clear All Data' dialog

apps/renderer/src/hooks/biz/useRouteParams.ts, apps/renderer/src/modules/entry-column/hooks.ts, apps/renderer/src/store/feed/hooks.ts, packages/components/src/atoms/route.ts
Replace the deprecated useRouteParams hook with useRouteParamsSelector to optimize performance and prevent unnecessary re-renders.
Update all relevant components to use the new hook.
=> refactor: update useRouteParams hook to prevent unnecessary re-renders

apps/renderer/src/components/ui/media.tsx
Fix https://github.com/RSSNext/Follow/issues/1757
Also related to https://github.com/RSSNext/Follow/pull/1760
Ensure that the default click behavior is prevented in the Media component to enhance user interaction.
=> fix: prevent default click behavior in Media

apps/renderer/src/modules/discover/form.tsx
Fixes #1761
Fix the issue #1761 
**The before,**
https://github.com/user-attachments/assets/86ff5303-7cea-478a-8ece-4012117e37f9
**The after effect,**
https://github.com/user-attachments/assets/2f42d011-e82a-44c1-a13c-00066c87b853
#1761
=> fix: When pasting the entire URL, auto adjust the URL prefix

apps/main/package.json, apps/main/src/lib/readability.ts, pnpm-lock.yaml
This pull-request is a fix for xss-security for readability.
Here is the [official declaration for readability xss security](https://github.com/mozilla/readability/security).
It mentioned,
> Note: as noted in the README.md file in this repository, readability itself does not intend to do security-related input sanitization, and you should use appropriate measures to sanitize input/output for your usecase.
So if the readability directly fetch the original html string, it may encounters the attack from potential vile xss code.
Therefore, I added a preprocessing process for readability with [DOMPurify](https://github.com/cure53/DOMPurify). When reading the original web page text, it first performs a DOM purification preprocessing process to avoid XSS code attacks.
=> fix(security): add dompurify for raw document string pre-cleaning on readability to avoid xss attack

apps/renderer/src/modules/entry-content/index.mobile.tsx, changelog/next.md
Resolved issue where back navigation to the pending view would not behave correctly after changing orientation in some device.
Before: after changing the orientation, the `BACK` button is navigate to previous feeds, which is expected to navigate to all feeds view. 
https://github.com/user-attachments/assets/92237fe1-706a-44bd-9425-4bf9b1f3ca7a
After: now the back navigation will be force pushed to previous feed list. 
https://github.com/user-attachments/assets/53278b62-bd29-4da9-9925-253d2ec8cf54
For some iPad users, using **Landscape** orientation to browser the list and preview on right, while using **Portrait** orientation for reading provides excellent experience. This PR will improve experience in this situation.
=> fix: handle popstate for navigation in mobile entry content

apps/renderer/src/modules/discover/form.tsx
The search button on the Discover page should become valid when user input
=> fix: discover form button disable state error

apps/renderer/src/modules/entry-content/header.desktop.tsx
Fixed an issue where scrolling caused the header's bottom border to appear, leading to a slight 1px shift of its content. 
No changes were made for mobile component since the element doesn't show after scrolling.
**Before**
**After**
=> fix(header): improve border visibility for meta display

apps/renderer/src/modules/entry-column/wrapper.desktop.tsx, apps/renderer/src/modules/entry-column/wrapper.shared.tsx
When reduceMotion is set to true, the feed column flickers when the feeds loads.
=> fix: feed column flickering

apps/renderer/src/components/common/Motion.tsx
Motion component should use transition prop in reduce motion mode,
For example,modal default animation type is 'spring',but the exit animation type should be 'tween'.
=> fix(animation): preserve exit transition for smoother animations

apps/renderer/src/components/ui/media.tsx
#2251 
The icon height is limited to max. 1.3em, which is perfect for me. May someone prefers to adjust it, just do it.
=> fix(media): adjust inline media size and alignment for better display #2251

apps/renderer/src/modules/player/corner-player.tsx
https://github.com/user-attachments/assets/ddef998c-be1b-485f-9418-644b5944d314
=> feat: add media session action handlers for play and pause

apps/main/package.json, apps/main/src/lib/readability.ts, pnpm-lock.yaml
This pull request fixed #2435 
For readability, it may encounters the decoding error.
**before:**
**After:**
The original code had some deficiencies in decoding the original webpage text. It only considered obtaining the charset attribute value from the `content type`. So I optimized the process of text encoding detection and decoding.
原来的代码中，对原网页文本解码存在一些不足，它仅仅考虑了从content type 中获得charset属性值。所以我优化了对文本编码检测和解码的流程。
---
Here’s the optimized code flow for detecting the charset and decoding the document:
1. **First, get the charset from the `Content-Type` response header.**  
2. **If the charset is not found in the headers, use `chardet` to detect the encoding.**  
1. **Get Charset from `Content-Type` Header**  
- Directly extract `charset` from the response header. This is the standard HTTP …
=> fix: fix decoding error(utf-8,gbk,iso-8859 and other charsets) in readability (issue #2435)

apps/main/src/lib/proxy.ts
Currently, `Session.setProxy` is not working for native fetch, which is used by readability.
So we need to set proxy for native fetch manually, refer to https://stackoverflow.com/a/76503362/14676508
Close #2375
=> feat: add proxy support for native fetch using undici

apps/renderer/src/atoms/context-menu.ts, apps/renderer/src/constants/shortcuts.ts, packages/utils/src/utils.ts
https://discord.com/channels/1243823539426033696/1319455653005230191/1328696880154022010
=> fix: enhance shortcut handling for OS compatibility

apps/renderer/src/modules/rsshub/set-modal-content.tsx
=> feat(rsshub): add minimum value to input field

apps/mobile/src/components/ui/context-menu/index.ios.tsx, apps/mobile/src/modules/context-menu/feeds.tsx, apps/mobile/src/modules/context-menu/lists.tsx, apps/mobile/src/modules/discover/RecommendationListItem.tsx, apps/mobile/src/modules/login/index.tsx, apps/mobile/src/modules/subscription/ViewTab.tsx
Refactor the context menu implementation to use the `zeego/context-menu` package, updating all relevant usages throughout the application.
This change enhances maintainability and aligns with the latest library standards.
=> refactor: migrate context menu to zeego/context-menu

apps/mobile/src/components/ui/pressable/item-pressable.tsx
- https://github.com/nandorojo/zeego/issues/61
- https://github.com/dominicstop/react-native-ios-context-menu/issues/9
=> fix(mobile): context menu crash when released too quickly

apps/mobile/src/components/native/webview/EntryContentWebView.tsx
I don't know why.......
https://github.com/user-attachments/assets/11b4d8d4-474d-4d78-9e05-da65299b0bb8
=> fix(mobile): can not load native module `FOSharedWebView`

apps/mobile/src/modules/entry-list/EntryListContentArticle.tsx, apps/mobile/src/modules/screen/atoms.ts, apps/mobile/src/modules/subscription/SubscriptionLists.tsx, apps/mobile/src/screens/(stack)/feeds/[feedId]/index.tsx, apps/mobile/src/store/collection/hooks.ts, apps/mobile/src/store/entry/store.ts
=> feat(mobile): implement collection entry list

apps/main/src/index.ts
Fixed a bug where the Follow window could not be reopened by clicking the Dock icon after closing it with CMD+W. This improves the macOS user experience by ensuring standard window management behavior.
This fix restores the expected macOS window management behavior where clicking the Dock icon should reopen a closed window.
=> refactor: update app activation event handling in Electron

apps/main/src/window.ts
Fixed a bug where the Follow window was always staying on top of other windows, which affected normal window management and user experience.
This fix ensures the Follow window follows normal window layering behavior.
=> feat(window): add alwaysOnTop property in createWindow function

apps/main/src/index.ts
=> fix: set auth cookie url filter

apps/mobile/src/screens/player.tsx
=> feat(mobile): player cover scale transition

apps/renderer/src/modules/entry-column/templates/list-item-template.tsx
=> fix: make icon center when media has play status

apps/mobile/src/modules/dialogs/MarkAllAsReadDialog.tsx, apps/mobile/src/modules/feed-drawer/atoms.ts
=> fix(mobile): can not mark view as read

apps/mobile/src/modules/entry-list/EntryListContentArticle.tsx, apps/mobile/src/modules/entry-list/EntryListContentPicture.tsx, apps/mobile/src/modules/entry-list/EntryListContentSocial.tsx, apps/mobile/src/modules/entry-list/EntryListContentVideo.tsx, apps/mobile/src/modules/entry-list/hooks.ts, apps/mobile/src/store/unread/store.ts
https://github.com/facebook/react-native/issues/30171
=> fix(mobile): onViewableItemsChanged is not reactive

apps/mobile/src/modules/entry-list/EntryListContentArticle.tsx, apps/mobile/src/modules/entry-list/EntryListContentPicture.tsx, apps/mobile/src/modules/entry-list/EntryListContentSocial.tsx, apps/mobile/src/modules/entry-list/EntryListContentVideo.tsx, apps/mobile/src/modules/entry-list/EntryListSelector.tsx, apps/mobile/src/modules/entry-list/hooks.ts
=> refactor(mobile): auto mark as read logic

apps/mobile/src/components/common/ModalSharedComponents.tsx, apps/mobile/src/modules/feed/FollowFeed.tsx, apps/mobile/src/screens/+native-intent.tsx
Resolve FOL-1681
Implement deep link handling to redirect users to the follow screen when the app is opened with a specific URI scheme.
https://github.com/user-attachments/assets/8b30c04b-cf54-42a9-9e04-b5855b314182
=> feat(mobile): add deep link redirection to follow screen

apps/mobile/app.config.ts, apps/mobile/src/atoms/settings/general.ts, apps/mobile/src/interfaces/settings/general.ts, apps/mobile/src/modules/entry-list/templates/EntryVideoItem.tsx, apps/mobile/src/modules/settings/routes/General.tsx, packages/utils/src/url-for-video.ts
Resolves FOL-1679
Introduce a setting to allow users to open YouTube and Bilibili videos in their respective apps instead of the in-app browser. This includes updates to settings management and video handling logic.
=> feat(mobile): add option to open videos in external apps

apps/mobile/drizzle/0016_curious_carnage.sql, apps/mobile/drizzle/meta/0016_snapshot.json, apps/mobile/drizzle/meta/_journal.json, apps/mobile/drizzle/migrations.js, apps/mobile/src/database/schemas/index.ts, apps/mobile/src/database/schemas/types.ts, apps/mobile/src/modules/entry-content/EntryContentHeaderRightActions.tsx, apps/mobile/src/morph/hono.ts, apps/mobile/src/morph/types.ts, apps/mobile/src/screens/(stack)/entries/[entryId]/index.tsx, apps/mobile/src/store/summary/store.ts
=> feat(mobile): perform actions

apps/desktop/src/renderer/src/modules/entry-content/index.shared.tsx
=> feat(desktop): hide progress when reading percent is zero

packages/utils/src/headers.ts
=> fix: can not play video in iframe

apps/desktop/src/renderer/src/hooks/biz/useEntryActions.tsx
https://github.com/user-attachments/assets/1bcbd581-e266-47a6-8059-d61ada0b3ffe
Close: #3005
=> fix(desktop): update shortcut for copying entry link

apps/mobile/src/modules/onboarding/feeds-english.json, apps/mobile/src/modules/onboarding/feeds.json, apps/mobile/src/modules/onboarding/preset.ts, apps/mobile/src/modules/onboarding/step-interests.tsx, apps/mobile/src/store/user/hooks.ts
Introduce language detection to provide users with preset feeds tailored to their language preferences during onboarding. English users receive a specific set of feeds, while others access a different collection.
=> feat(mobile): implement language-based preset feeds for onboarding

apps/desktop/src/renderer/src/modules/command/hooks/use-command.ts, apps/desktop/src/renderer/src/modules/entry-content/actions/more-actions.tsx
=> feat(desktop): hide separator when availableActions is empty

apps/desktop/src/renderer/index.html, apps/ssr/index.html
For some reason, the name of the `favicon.svg`, which was supposed to be the main favicon resource for this project, was changed. For a long time, the project had been using a fallback `.ico` icon.
However, it seems that Firefox did not handle compatibility well, even when the fetched SVG was missing or incorrect, it did not fallback to the `.ico` icon.
close #3139
=> fix(desktop): incorrect svg favicon name

apps/desktop/src/renderer/src/atoms/player.ts
When you quit the app, though it has stored `currentTime` value. `currentTime` will be 0 after you click the play button.
Before:
https://github.com/user-attachments/assets/153ec89e-becb-48bc-a447-36fdae166d4c
After:
https://github.com/user-attachments/assets/5736fb7e-f99d-4bac-9631-fd97105383a3
=> fix(desktop): handle audio metadata loading and reset current time

apps/desktop/src/renderer/src/constants/shortcuts.ts
=> fix(desktop): update zen mode shortcut key notation

apps/desktop/src/renderer/src/components/ui/media/preview-media.tsx
=> fix: hide video preview's action overlay

apps/desktop/src/renderer/src/modules/auth/Form.tsx
Cause the login form check not as expected
When not logged in, in the login form, clicking the Sign up button causes a form submission. This is clearly attributable to an incorrect button type setting or the utilization of the default value.
Just added a `type` attribute with the value "button" to the Sign up button.
I suggest for future development, consider using lint to prevent this issue. Or, specify a default `type` to replace the standard default "submit", only explicitly triggering the submit action when submission is actually needed, or detach the button from the form.
=> fix(desktop): add type attribute to sign up button

apps/desktop/src/renderer/src/modules/app-layout/subview/index.electron.tsx, apps/desktop/src/renderer/src/modules/timeline-column/index.tsx
This PR fixes the navigation status when entering from pages like action or discover.
- Can not go back to home
- No fallback subscription list
=> fix: navigation status when entering from other pages

apps/desktop/src/renderer/src/modules/customize-toolbar/constant.ts, apps/desktop/src/renderer/src/modules/customize-toolbar/modal.tsx, apps/desktop/src/renderer/src/modules/entry-content/header.electron.tsx, apps/desktop/src/renderer/src/modules/entry-content/header.mobile.tsx, apps/desktop/src/renderer/src/modules/settings/tabs/apperance.tsx
Streamline the order of toolbar actions using a Set, add a customization option for toolbar actions in settings, and ensure only the main action displays in mobile view.
=> refactor: enhance toolbar customization and mobile view actions

apps/desktop/src/renderer/src/components/ui/markdown/renderers/MarkdownP.tsx, apps/desktop/src/renderer/src/modules/entry-content/components/EntryTitle.tsx
=> feat(desktop): add estimated audio duration display for entry-title

apps/mobile/src/screens/(modal)/onboarding/select-reading-mode.tsx
Update the SelectReadingModeScreen to use SafeNavigationScrollView for improved navigation handling.
=> fix(mobile): replace SafeModalScrollView with SafeNavigationScrollView in SelectReadingModeScreen

apps/mobile/src/components/layouts/header/NavigationHeader.tsx
Resolve FOL-1773
Refine the flex styles in the NavigationHeader component to improve layout consistency and responsiveness.
=> fix: adjust flex styles in NavigationHeader layout

apps/desktop/src/renderer/src/modules/entry-content/components/EntryTitle.tsx
Related: #3292
Add a `ts-expect-error`  tag that made me forget to import this method.
=> fix(desktop): miss related methods in entry-title

apps/desktop/src/renderer/src/modules/wallet/balance.tsx, apps/mobile/src/components/common/Balance.tsx, packages/utils/src/utils.spec.ts, packages/utils/src/utils.ts
Fix https://github.com/RSSNext/Folo/issues/2754
=> fix: add locale support for balance formatting

apps/desktop/src/main/src/lib/tray.ts, apps/desktop/src/main/src/logger.ts, apps/desktop/src/renderer/src/components/ui/media/preview-media.tsx, apps/desktop/src/renderer/src/hooks/biz/useTraySetting.ts
Set the default option to minimize the app to the tray and improve logging for app quit events. Additionally, enhance pointer events handling in the image component.
Fix https://github.com/RSSNext/Folo/issues/3183
=> chore: enhance desktop

apps/desktop/src/renderer/src/modules/settings/modal/layout.tsx
I found that Folo has already encapsulated the `useResizeableModal` method for the second time, naming it `useModalResizeAndDrag`, so we can use `useModalResizeAndDrag` more conveniently.
=> refactor(desktop):  update SettingModalLayout with new hooks for drag and resize

apps/desktop/src/renderer/src/modules/command/commands/entry.tsx, locales/app/ar-DZ.json, locales/app/ar-IQ.json, locales/app/ar-KW.json, locales/app/ar-MA.json, locales/app/ar-SA.json, locales/app/ar-TN.json, locales/app/de.json, locales/app/en.json, locales/app/es.json, locales/app/fi.json, locales/app/fr.json, locales/app/it.json, locales/app/ja.json, locales/app/ko.json, locales/app/pt.json, locales/app/ru.json, locales/app/tr.json, locales/app/zh-CN.json, locales/app/zh-HK.json, locales/app/zh-TW.json
The "Export as PDF" feature uses the `window.print()` method, which cannot determine whether the user has successfully exported the PDF. The current toast message is misleading, so it is recommended to remove it.
=> fix(desktop): remove incorrect PDF export notification

apps/mobile/src/modules/context-menu/feeds.tsx, apps/mobile/src/modules/subscription/CategoryGrouped.tsx
Wrap the SubscriptionFeedCategoryContextMenu in a View for better layout control and add asChild and style props to ContextMenu.Trigger for improved customization options.
Before
After
=> fix: wrap SubscriptionFeedCategoryContextMenu in a View

apps/mobile/app.config.ts, apps/mobile/scripts/with-gradle-jvm-heap-size-increase.js
Enhance the mobile app's build stability by increasing the JVM heap size in the Gradle configuration. This change addresses random build failures.
=> fix(mobile): improve build stability

apps/mobile/app.config.ts, apps/mobile/src/App.tsx
Introduce a translucent status bar in the mobile application to enhance the visual experience. This change modifies the app configuration and updates the main app component accordingly.
=> fix(mobile): add translucent status bar

apps/desktop/src/renderer/src/modules/entry-column/layouts/EntryListHeader.shared.tsx, apps/mobile/src/modules/settings/routes/ManageList.tsx, locales/app/zh-CN.json
When I adjusted the number of columns using the masonry layout, I encountered an issue where the slider movement did not take effect. I found that this has been a persistent problem with the official component's `onValueCommit` interface, which is discussed in this [issue](https://github.com/radix-ui/primitives/issues/1760). 
I tried using the stable `onValueChange` interface to configure the debounce method instead of onValueCommit. Although this eliminates a value comparison step, there is at least no difference in user experience.
Before:
https://github.com/user-attachments/assets/82cb75d3-d908-404c-a915-ae5e4e60af08
After:
https://github.com/user-attachments/assets/cc5f3bba-26ad-4886-93e4-82baa5b6de6f
=> fix(desktop): masonry layout Slide component sometimes not working

apps/desktop/src/renderer/src/modules/entry-content/header.electron.tsx
In terms of social media, the height of the functional button area at the top of the details section changed from 32px to 33px, which is quite annoying. I fixed this issue by removing the 1px border at the bottom of this block.
Before:
https://github.com/user-attachments/assets/f1a9aa29-8dd4-4ea2-b699-98b109ab0b60
After:
https://github.com/user-attachments/assets/48686d01-d68a-499f-9a1c-5f962075dca2
=> style(desktop): optimize entry content header 1px offset

apps/desktop/src/renderer/src/modules/discover/form.tsx
Related: https://github.com/RSSNext/Folo/commit/87d37f9f68a0bbb79479ea9a636ffbd7dd9d92b1
I think this new layout makes footer wide.
After:
=> feat(desktop): update SearchCard layout

apps/desktop/src/renderer/src/lib/translate.ts, apps/mobile/package.json, apps/mobile/src/lib/translation.ts, apps/mobile/src/modules/entry-content/EntryContentHeaderRightActions.tsx, apps/mobile/src/modules/entry-list/EntryListContentArticle.tsx, apps/mobile/src/modules/entry-list/EntryListContentPicture.tsx, apps/mobile/src/modules/entry-list/EntryListContentSocial.tsx, apps/mobile/src/modules/entry-list/EntryListContentVideo.tsx, apps/mobile/src/modules/entry-list/hooks.ts, apps/mobile/src/screens/(stack)/entries/[entryId]/index.tsx, apps/mobile/src/store/action/hooks.ts, apps/mobile/src/store/entry/hooks.ts, apps/mobile/src/store/translation/hooks.ts, apps/mobile/src/store/translation/store.ts, pnpm-lock.yaml
=> fix(mobile): optimize translation query

apps/desktop/src/renderer/src/components/ui/modal/stacked/modal.tsx
As you can see if we update the state ourselves it will has flash on the screen.
The component will auto unmount after closing. We don't need to handle it ourselves. 
https://github.com/user-attachments/assets/ee2f7fde-447a-402c-a23a-0cf80b9aba19
=> fix(modal): remove unnecessary state update

packages/components/src/ui/platform-icon/collections/cubox.tsx
Replaced the Cubox icon in the project with a modified version of the official SVG.
Modifications to the official SVG include:
- Removed the "Cubox" text element.
- Removed the explicit white background element.
- Changed the icon's main background fill from the original gradient to `currentColor` for better theme adaptability.
official SVG and preview
=> feat: Replace Cubox icon with optimized official SVG version

apps/desktop/src/renderer/src/modules/command/commands/entry.tsx
=> feat(desktop): enhance sharing functionality with title and description

apps/desktop/src/renderer/src/modules/ai/ai-daily/daily.tsx
This button is not meaningful here. In source code, it need to get `feedId` from route, but in daily summary page we don't have this.
=> chore(desktop): drop mark as read button in ai-daily

apps/desktop/src/renderer/src/modules/shared/ViewSelectorRadioGroup.tsx
Blame to https://github.com/RSSNext/Folo/pull/3265
This pull request updates the `ViewSelectorRadioGroup` component in `ViewSelectorRadioGroup.tsx` to improve the handling of feed and entry states, ensuring clearer logic for displaying preview content or loading indicators.
=> fix: improve loading and preview logic in ViewSelectorRadioGroup

apps/desktop/src/renderer/src/modules/wallet/balance.tsx, packages/utils/src/utils.spec.ts, packages/utils/src/utils.ts
Blame to https://github.com/RSSNext/Folo/pull/3319
This pull request updates the `toScientificNotation` utility function, modifying the function to enforce a fixed two-decimal format and updating test cases to validate the new behavior.
=> fix: keep only two decimal places at most for balance

apps/mobile/src/modules/ai/summary.tsx
Adjust the opacity modifier for the background in the Android version of the app to ensure proper styling.
=> fix: summary syles in android

apps/mobile/app.config.ts, apps/mobile/plugins/with-android-day-night-theme-plugin.js
Also related to https://github.com/nandorojo/zeego/issues/150
Introduce a plugin to support day/night theme styling for the Android app, enhancing the user interface experience.
This addition prepares the app for future updates to Expo.
=> fix(android): add day/night theme plugin for Android styling

apps/desktop/src/renderer/src/hooks/biz/useEntryActions.tsx, apps/desktop/src/renderer/src/modules/customize-toolbar/dnd.tsx, locales/app/en.json, locales/app/zh-CN.json
1. `copyTitle` action is missing in header actions. 
Close: #3569
After:
2.  For `tts`, it is hiden in browser or mobile. But it exists in custom toolbar, so I add a tip here.
=> feat(desktop): add copy title action and tooltip warning

apps/desktop/layer/renderer/src/modules/discover/recommendations.tsx
The close btn is covered by content.
=> fix(desktop): add z-index to close button for proper stacking

apps/desktop/layer/renderer/src/modules/discover/DiscoverFeedForm.tsx
When I add a new feed and click the preview button, nothing occurs. It claims I failed to enter the parameter, yet in reality, I have indeed provided it.
I discover that the input field does not properly bind to the value change event.
Before:
After:
https://github.com/user-attachments/assets/50f51c85-d292-4e2b-87b7-ef56e76677a9
=> fix(desktop): preview feature is invaliable in discover

apps/desktop/layer/renderer/src/modules/entry-column/list.tsx
before:
https://github.com/user-attachments/assets/d631e2cb-b6ae-42ab-bb08-f2d25fb16fb4
after:
https://github.com/user-attachments/assets/8ee0890c-eb62-4891-9893-8ba0563d81fd
⬆️  In the above code, feedId is used as the key to save the offset value. However, if change the feed view in Header, the feedId will be 'all', always 'all', so, In this situation, keep scroll position is inaccurate
my solution is to change the key to use `${view}-${feedId}`
=> fix(desktop): EntryList Component keep scroll position is inaccurate

apps/desktop/layer/renderer/src/components/ui/code-highlighter/shiki/Shiki.tsx, apps/desktop/layer/renderer/src/lib/parse-html.ts
Implement a workaround for Hugo's code block rendering issues, ensuring proper handling of line numbers and visibility of the copy button in the code highlighter.
Related entry https://app.follow.is/timeline/view-0/140318102626016256/140318102651182082
Before
After
=> fix: handle Hugo code block workaround

apps/desktop/layer/renderer/src/modules/entry-column/grid.tsx
- before:
- video to picture:
picture was squeezed together.
https://github.com/user-attachments/assets/402d3c36-72b8-422a-8d47-d80dc1917541
- picture to video:
the gap for video is so big.
https://github.com/user-attachments/assets/be7f0532-8e89-4c5f-9ac5-a10c7315c7c4
- after:
now should looks fine 😄 
https://github.com/user-attachments/assets/6e3bf1e0-4999-4876-b4a8-fed9f51277b0
related to #2573
=> fix(grid-entry): fix rowVirtualizer not proper refresh when view change

apps/desktop/layer/renderer/src/providers/setting-sync.tsx
Close: #3622
Font family names that include whitespace or other special characters (like &, !, #) must be quoted. For example, "Times New Roman" or 'Arial Black'.
https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#valid_family_names
=> fix(desktop): font names that include whitespace must be quoted

apps/desktop/plugins/vite/utils/i18n-completeness.ts
=> fix(desktop): improve comprehension for i18n progress

apps/desktop/layer/renderer/src/modules/discover/DiscoverFeedCard.tsx, apps/desktop/layer/renderer/src/modules/discover/DiscoverForm.tsx
I only check  `DiscoverFeedCard` for the discover page . I don't know if there are any effects to other pages.
| Before | After |
| --- | ---- |
| <img src="https://github.com/user-attachments/assets/5fbe3119-c408-462f-be4e-4d6d34e0f355" /> | <img src="https://github.com/user-attachments/assets/83f120c9-6eaf-465b-9bdc-bb91ba94b44b" /> |
=> fix(discover): borken style in discover page

apps/desktop/layer/renderer/src/modules/renderer/html.tsx
I use relative path in my blog writing, it start with `.` such like:
```html
<a href="../some-magic-connections">some text</a>
```
but folo can't handle proper, like this:
After fix, now should look better:
I also find the latest code can't run in browser, so i temporarily set my dev branch to server days ago, to avoid it.
=> fix(link): fix link start with '.' don't handle proper

apps/desktop/layer/renderer/src/hooks/biz/useNavigateEntry.ts, apps/desktop/layer/renderer/src/modules/entry-column/layouts/EntryItemWrapper.tsx
- **chore(ssr): update global constants and clean up imports**
- **feat: redeisgn og**
- **refactor(desktop): rename and restructure navigation functions for clarity**
- **feat(desktop): add debug logging in EntryItemWrapper for click handling**
- **refactor(desktop): remove debug logging from handleClick in EntryItemWrapper**
- **cleanup**
=> fix: try fix can not navigation inbox item in prod

apps/desktop/layer/renderer/src/modules/entry-column/Items/social-media-item.tsx
1. Avoid triggering `mouseleave` when the mouse moves from a parent element to a child element positioned with `absolute`.
2. Close the dropdown menu and hide the action bar when clicking outside.
3.  Add a transition effect to the action bar when its visibility changes.
Before:
https://github.com/user-attachments/assets/5579e7f7-3c9e-4714-ba08-cbdf3a3481aa
After: 
https://github.com/user-attachments/assets/f4d81164-bc17-4fa4-90c7-7d62d2ff69ea
=> fix(desktop): improve action bar's visibility logic

apps/desktop/layer/renderer/src/components/ui/media/PreviewMediaContent.tsx
This [code](https://github.com/RSSNext/Follow/blob/main/apps/desktop/layer/renderer/src/components/ui/media/PreviewMediaContent.tsx#L388) has passed `loading` here. But it doesn't pass to its child properly.
=> feat(desktop): pass loading prop correctly

apps/desktop/layer/renderer/src/components/ui/media/PreviewMediaContent.tsx, apps/desktop/layer/renderer/src/modules/entry-column/Items/social-media-item.tsx
This PR contain two changes:
- because the 'read more' button in social-media is contained by a `<a>` tag, maybe this will cause a refresh? (i can't make sure, because dev version not refresh, but release version refresh, require further discussion, this is related to #4006 ), and change `SocialMediaItemSkeleton` to function component.
- add opacity for preview-media message, see picture:
=> fix: fix social media click Read more refresh

apps/mobile/app.config.ts
Fix https://github.com/RSSNext/Folo/issues/3908
Implement support for Android adaptive icons by adding a monochrome image option in the app configuration.
Learn more: https://docs.expo.dev/develop/user-interface/splash-screen-and-app-icon/#android
=> feat: support Android adaptive icon

apps/mobile/src/components/lightbox/ImageViewing/components/ImageItem/ImageItem.android.tsx, apps/mobile/src/components/lightbox/ImageViewing/components/ImageItem/ImageItem.ios.tsx, apps/mobile/src/components/native/GaleriaAccessory/EntryGaleriaAccessory.tsx, apps/mobile/src/components/ui/carousel/MediaCarousel.tsx, apps/mobile/src/components/ui/image/Image.tsx, apps/mobile/src/modules/entry-list/templates/EntryPictureItem.tsx
Replace the existing Image component with ProxyImage to enhance performance and styling. Update styles in the Image component and improve layout in the ImageItem component.
=> fix: improved lightbox component for iOS

apps/desktop/layer/renderer/src/components/ui/media/PreviewMediaContent.tsx
Close: #4084 
It seems don't want to have a download button in website.
https://github.com/RSSNext/Folo/commit/cf72753b590b3197c0a9cc7f2b44c411efc72e08#diff-f20c78d077ecc258ffb0acd961771b6bfe4f0248b4972deb340c5adfd7e4edb4L113-L122
=> feat(desktop): only approve download in desktop not website

apps/desktop/layer/main/package.json, apps/desktop/layer/main/src/ipc/services/integration.ts, pnpm-lock.yaml
Fix https://github.com/RSSNext/Folo/issues/4148
Refactor file name processing to use a custom `sanitizeFileName` function instead of the `slugify` library, and remove the unused `slugify` dependency.
=> fix: replace slugify with sanitizeFileName for file name processing

apps/desktop/layer/renderer/src/modules/entry-column/EntryColumnShortcutHandler.tsx
Display a notification upon clicking switch buttons when the entry is either the first or the last
=> feat: add notification for timeline switch

apps/desktop/layer/renderer/src/@types/default-resource.electron.ts
- Fixed AI settings page showing translation keys instead of translated text in Electron build
- Added missing AI namespace translations to Electron default resources
In the Electron app, the AI settings page was displaying translation keys (e.g., `personalize.title`, `shortcuts.add`) instead of the actual translated text. This was because the AI translations were missing from the Electron-specific default resources file.
- Added `ai_en` and `ai_ja` imports to `default-resource.electron.ts`
- Included AI translations in all language configurations
- Used English fallback for Chinese languages until specific translations are available
Before: Translation keys were shown instead of text
After: Proper translations are displayed
=> fix: add missing AI translations for Electron build

apps/desktop/layer/renderer/src/modules/entry-column/Items/audio-item.tsx
in https://github.com/RSSNext/Folo/commit/0e456d5b7368bbc050e75bd580266f13fb62d016#diff-d6734654ec584a44e9347c866aecae2779274875017377b9a5cc534138cff4fe the Audio item was not add corresponding style, cause not enough padding, This PR fix it.
Before：
After:
=> fix: fix Audio item layout

apps/desktop/layer/renderer/src/modules/settings/tabs/integration/CustomIntegrationSection.tsx, apps/desktop/layer/renderer/src/modules/settings/tabs/integration/index.tsx
- When custom integration is disabled, only show built-in integrations in filters.
- When custom integration is enabled, show all integrations (both built-in and custom) in filters.
<table>
<tr>
<td>
Disabled
<td>
<td>
<tr>
<td>
Enable
<td>
<td>
</table>
=> feat(desktop): improve integration settings search with empty states

apps/desktop/layer/renderer/src/components/ui/modal/inspire/PeekModal.tsx, apps/desktop/layer/renderer/src/components/ui/peek-modal/EntryModalPreview.tsx, apps/desktop/layer/renderer/src/hooks/biz/usePeekModal.tsx
Before: The modal shows up only after the content loads, with no loading state shown in between — that’s not a good ux.
After: Displaying a skeleton while loading improves the user experience.
<table>
<tr>
<td>
Before
<td>
After
<tr>
<td>
https://github.com/user-attachments/assets/c4a6e5c0-7279-4f35-8be9-d86f0ee37b40
<td>
https://github.com/user-attachments/assets/5ff2c5c8-ce79-4851-8a52-2902532a55cb
</table>
=> feat(desktop): optimize PeekModal loading experience

apps/mobile/package.json, apps/mobile/src/modules/discover/Recommendations.tsx, apps/mobile/src/modules/entry-list/EntryListContentArticle.tsx, apps/mobile/src/modules/entry-list/EntryListContentPicture.tsx, apps/mobile/src/modules/entry-list/EntryListContentSocial.tsx, apps/mobile/src/modules/entry-list/EntryListContentVideo.tsx, apps/mobile/src/modules/entry-list/EntryListSelector.tsx, apps/mobile/src/modules/entry-list/hooks.ts, apps/mobile/src/modules/screen/TimelineSelectorList.tsx, apps/mobile/src/modules/subscription/SubscriptionLists.tsx, package.json, pnpm-lock.yaml
Upgrade the FlashList library to version 2.0.0 and update the package manager to pnpm@10.14.0. Adjust type imports and references throughout the codebase to accommodate the new version.
Learn more: https://shopify.github.io/flash-list/docs/v2-migration/
https://shopify.github.io/flash-list/docs/v2-changes
https://shopify.engineering/flashlist-v2
=> refactor: upgrade FlashList to v2

apps/desktop/layer/renderer/src/components/ui/markdown/renderers/MarkdownLink.tsx
=> fix(desktop): make copy button center in markdown-link component

apps/desktop/layer/renderer/src/modules/entry-column/hooks/useLocalEntries.ts
Correct a type error in the `useLocalEntries` hook by ensuring the default value for `view` is set properly and adjusting the fetchNextPage assignment.
=> fix: type error

pnpm-workspace.yaml
Ensure that the `ignorePatchFailures` option is set to false in the pnpm workspace configuration to prevent patch failures from being ignored.
=> chore: set ignorePatchFailures to false

apps/desktop/layer/renderer/src/components/ui/modal/stacked/modal.tsx
<table>
<tr>
<td>
Before
<td>
<tr>
<td>
After
<td>
</table>
=> feat: enhance modal layout with improved styling and structure

apps/mobile/src/modules/feed/FollowFeed.tsx
Fixes #4483.
On mobile, there is a `useEffect` which resets the form values, and it was removing all properties other than `view`. I've updated it to now include all of the default values when resetting.
=> fix: preserve unchanged fields when editing feed on mobile
