RSSNext/Folo

src/renderer/src/components/entry-content/index.tsx

`3.5 rem` is the same height as EntryShare

fix: content height

---

src/renderer/src/components/entry-column/index.tsx
src/renderer/src/components/entry-column/item-wrapper.tsx
src/renderer/src/components/feed-column/category.tsx
src/renderer/src/components/feed-column/index.tsx
src/renderer/src/components/feed-column/item.tsx
src/renderer/src/components/feed-column/list.tsx
src/renderer/src/contexts/outlet/main-layout.tsx
src/renderer/src/lib/types.ts
src/renderer/src/pages/(main)/(context)/index.tsx
src/renderer/src/pages/(main)/(context)/layout.tsx
src/renderer/src/pages/(main)/layout.tsx

For better typescript intelligence and maintenance

refactor: extract outlet context as a outside context

---

eslint.config.mjs
src/renderer/src/hono.ts
src/renderer/src/lib/types.ts
src/renderer/src/queries/api-fetch.ts
src/renderer/src/queries/subscriptions.ts

In this PR, I use generated type for hono RPC. I added a usage example and we can migrate incrementally.

refactor: typesafe api call

---

cssAsPlugin.js
package.json
pnpm-lock.yaml
src/renderer/src/assets/base.css
src/renderer/src/assets/tailwind-extend.css
src/renderer/src/components/entry-column/article-item.tsx
src/renderer/src/components/entry-column/item-wrapper.tsx
src/renderer/src/components/entry-content/index.tsx
src/renderer/src/pages/(main)/(context)/index.tsx
src/renderer/src/pages/(main)/(context)/layout.tsx
tailwind.config.cjs

This pr modified some styles in dark mode, and use `cssPlugin` to write tailwindcss atom class for IntelliSense

fix: dark mode style

---

src/renderer/src/hono.ts
src/renderer/src/queries/entries.ts
src/renderer/src/queries/subscriptions.ts

Based on this pr https://github.com/RSSNext/follow-server/pull/10

fix: remove `code == 1` logic

---

package.json
pnpm-lock.yaml
src/renderer/src/components/entry-column/article-item.tsx
src/renderer/src/components/entry-column/index.tsx
src/renderer/src/components/entry-column/item-wrapper.tsx
src/renderer/src/components/entry-column/notification-item.tsx
src/renderer/src/components/entry-column/picture-item.tsx
src/renderer/src/components/entry-column/social-media-item.tsx
src/renderer/src/components/entry-column/types.ts
src/renderer/src/components/entry-column/video-item.tsx
src/renderer/src/hooks/useUpdateEntry.tsx
src/renderer/src/lib/ns.ts
src/renderer/src/lib/types.ts

To resolves https://discord.com/channels/1243823539426033696/1243823761913020458/1245445062553370624
And fix vlist render item, extract vlist component outside to the parent component

feat: mark read out of scroll

---

electron.vite.config.ts
src/main/index.ts
src/main/window.ts
src/renderer/index.html
src/renderer/src/components/discover/form.tsx
src/renderer/src/components/entry-column/index.tsx
src/renderer/src/components/entry-column/video-item.tsx
src/renderer/src/components/feed-column/list.tsx
src/renderer/src/components/ui/autocomplete.tsx
src/renderer/src/components/ui/switch.tsx
src/renderer/src/lib/constants.tsx
src/renderer/src/lib/enum.ts
src/renderer/src/pages/(external)/feed/index.tsx
src/renderer/src/pages/(external)/redirect.tsx
src/renderer/src/pages/(main)/(context)/layout.tsx
src/renderer/src/pages/add/index.tsx
src/renderer/src/pages/settings/layout.tsx
src/renderer/src/store/entry.ts
src/renderer/src/styles/base.css
src/shared/src/constants.ts
src/shared/src/electron.ts
src/shared/src/index.ts
tailwind.config.cjs
tsconfig.node.json
tsconfig.web.json

1. Support sidebar vibrancy for macOS
2. Add skeleton when app loading
3. Theme accent in tailwindcss config
1. Video page layout

feat: macos vibrancy

---

src/renderer/src/components/entry-column/index.tsx
src/renderer/src/store/entry.ts
src/renderer/src/store/subscription.ts

Solved read all handling logic based on view or category.
NOTE:
Changed the structure of the Store, may throw an error, need to clean up indexeddb

fix: read all logic

---

src/renderer/src/pages/(external)/login.tsx

Fixes https://github.com/RSSNext/follow/issues/39

fix: google login

---

src/renderer/src/components/feed-column/index.tsx
src/renderer/src/components/feed-column/list.tsx
src/renderer/src/hono.ts
src/renderer/src/store/unread.ts

1. Fix feed column click and stopPropagation on actions
2. Fix unread store not update when feed hadn't count before

fix: click area and unread count store bug

---

src/renderer/src/components/entry-column/item-wrapper.tsx
src/renderer/src/components/feed-column/list.tsx
src/renderer/src/hono.ts
src/renderer/src/hooks/useEntryActions.tsx
src/renderer/src/queries/subscriptions.ts
src/renderer/src/store/entry.ts
src/renderer/src/store/unread.ts

1. Extract entry action hook
2. Fix entry item read mutation, should use entry action's read action
3. Batch unread count api, refer https://github.com/RSSNext/follow-server/pull/16

fix: unread mutation

---

src/renderer/src/components/entry-column/index.tsx
src/renderer/src/components/entry-column/item.tsx
src/renderer/src/components/entry-content/index.tsx
src/renderer/src/pages/add/index.tsx
src/renderer/src/store/entry/hooks.ts

`useEntry` guard and loading more indicator
https://github.com/RSSNext/follow/assets/41265413/d86a576a-a80a-4018-844c-e1cead8d5edb

fix: entry guard and loading more

---

src/renderer/src/store/subscription.ts

fix: fetch by view long task

---

src/renderer/src/components/entry-column/index.tsx

fix: empty list lead ui freeze

---

src/renderer/src/components/ui/button/index.tsx
src/renderer/src/components/ui/button/variants.tsx
src/renderer/src/components/ui/switch.tsx
src/renderer/src/hono.ts
src/renderer/src/modules/discover/feed-form.tsx
src/renderer/src/modules/discover/form.tsx
src/renderer/src/modules/feed-column/item.tsx
src/renderer/src/styles/colors.css
tailwind.config.cjs

Fix onSuccess callback logic when using modal form to add/modify Follow.
Fix the color of StyledButton in light/dark.

fix: `FollowForm` modal logic

---

src/renderer/index.html
src/renderer/src/components/ui/autocomplete.tsx
src/renderer/src/components/ui/background/vibrancy.tsx
src/renderer/src/components/ui/button/variants.tsx
src/renderer/src/components/ui/command.tsx
src/renderer/src/components/ui/image/index.module.css
src/renderer/src/components/ui/input/Input.tsx
src/renderer/src/components/ui/navigation-menu.tsx
src/renderer/src/components/ui/sonner.tsx
src/renderer/src/components/ui/switch.tsx
src/renderer/src/components/ui/tabs.tsx
src/renderer/src/components/user-button.tsx
src/renderer/src/modules/entry-column/item.tsx
src/renderer/src/pages/(main)/(context)/layout.tsx
src/renderer/src/pages/add/index.tsx
src/renderer/src/pages/settings/layout.tsx
src/renderer/src/styles/colors.css
src/renderer/src/styles/tailwind.css
tailwind.config.ts

Should add `<alpha-value>` to `hsl`, let alpha value work.
```
hsl(var(--border) / <alpha-value>)
```
And, adjust themed color to hsl color string, make tw-opactiy work

fix: tailwind color alpha value

---

src/renderer/src/components/ui/button/index.tsx
src/renderer/src/components/ui/kbd/Kbd.tsx
src/renderer/src/hooks/biz/useEntryActions.tsx
src/renderer/src/lib/shortcuts.ts
src/renderer/src/lib/utils.ts
src/renderer/src/modules/discover/form.tsx
src/renderer/src/modules/entry-column/index.tsx
src/renderer/src/modules/entry-content/header.tsx
src/renderer/src/modules/feed-column/index.tsx
src/renderer/src/pages/settings/shortcuts.tsx
src/renderer/src/styles/colors.css
src/renderer/src/styles/tailwind-extend.css

Added new styles for kbd.
Modified shortcut usage of `<ActionButton />`
Deleted the `Tab` shortcut key for view switching. The `Tab` key should be used to switch between page elements, which is beneficial to a11y

feat: new kbd design and refactor kbd logic

---

package.json
pnpm-lock.yaml
src/renderer/src/components/ui/context-menu/context-menu.tsx
src/renderer/src/components/ui/context-menu/index.ts
src/renderer/src/components/ui/input/Input.tsx
src/renderer/src/components/ui/input/TextArea.tsx
src/renderer/src/components/ui/tooltip.tsx
src/renderer/src/components/ui/typography/EllipsisWithTooltip.tsx
src/renderer/src/components/ui/typography/index.ts
src/renderer/src/lib/native-menu.ts
src/renderer/src/lib/utils.ts
src/renderer/src/modules/entry-column/index.tsx
src/renderer/src/modules/entry-content/index.tsx
src/renderer/src/modules/feed-column/index.tsx
src/renderer/src/pages/(main)/layout.tsx
src/renderer/src/pages/settings/layout.tsx
src/renderer/src/providers/context-menu-provider.tsx
src/renderer/src/providers/root-providers.tsx
src/renderer/src/styles/tailwind-extend.css

Support for displaying compatible electron menus in web apps.

feat: web context menu

---

.vscode/settings.json
eslint.config.mjs
package.json
pnpm-lock.yaml
src/renderer/src/components/ui/auto-completion/AutoCompletion.tsx
src/renderer/src/modules/entry-content/index.tsx
src/renderer/src/modules/settings/action-card.tsx

Make sure eslint vscode is updated to 3.0.8

chore: update lint config

---

package.json
pnpm-lock.yaml
src/main/menu.ts
src/main/tipc.ts
src/main/window.ts
src/renderer/src/components/header.tsx
src/renderer/src/components/ui/button/index.tsx
src/renderer/src/components/ui/dropdown-menu/dropdown-menu.tsx
src/renderer/src/components/ui/image.tsx
src/renderer/src/components/ui/modal/stacked/modal.tsx
src/renderer/src/components/user-button.tsx
src/renderer/src/hooks/biz/useEntryActions.tsx
src/renderer/src/lib/client.ts
src/renderer/src/lib/native-menu.ts
src/renderer/src/modules/discover/feed-form.tsx
src/renderer/src/modules/feed-column/index.tsx
src/renderer/src/modules/settings/modal/content.tsx
src/renderer/src/modules/settings/modal/hooks.ts
src/renderer/src/modules/settings/title.tsx
src/renderer/src/pages/(external)/redirect.tsx
src/renderer/src/pages/settings/actions.tsx
src/renderer/src/pages/settings/index.tsx
src/renderer/src/pages/settings/profile.tsx
src/renderer/src/pages/settings/shortcuts.tsx

https://github.com/RSSNext/follow/assets/41265413/4849559b-abfb-42a3-8192-10ac17320f85

feat: user profile dropmenu and setting modal in web app

---

package.json
pnpm-lock.yaml
src/renderer/src/components/common/LoadRemixAsyncComponent.tsx
src/renderer/src/components/ui/modal/stacked/hooks.tsx
src/renderer/src/components/ui/modal/stacked/modal.tsx
src/renderer/src/components/ui/modal/stacked/types.tsx
src/renderer/src/components/ui/scroll-area/ScrollArea.tsx
src/renderer/src/components/ui/scroll-area/index.ts
src/renderer/src/components/ui/scroll-area/useMaskScrollArea.ts
src/renderer/src/modules/settings/modal/content.tsx
src/renderer/src/modules/settings/modal/layout.tsx
src/renderer/src/modules/settings/tabs/apperance.tsx
src/renderer/src/store/ui.ts

Make `<Modal />` more usefully. and support modal draggable.

feat: modal appearance

---

src/renderer/src/modules/discover/content-components.tsx
src/renderer/src/modules/discover/recommendations-card.tsx

feat: Support for generating Select components based on data

---

src/renderer/src/lib/path-parser.test.ts
src/renderer/src/lib/path-parser.ts
src/renderer/src/modules/discover/content-components.tsx
src/renderer/src/modules/discover/example-data.json

Signed-off-by: Innei <i@innei.in>

fix: add path parser options, test case, fix some styles, make select can focus

---

src/renderer/src/components/ui/image.tsx

For the GitHub feed, https://github.com/diygod.atom
Before
After

fix: fixed size image

---

src/renderer/src/hooks/biz/useAsRead.ts
src/renderer/src/hooks/biz/useEntryActions.tsx
src/renderer/src/hooks/biz/useNavigateEntry.ts
src/renderer/src/hooks/biz/useRouteParams.ts
src/renderer/src/lib/constants.tsx
src/renderer/src/lib/utils.ts
src/renderer/src/modules/entry-column/index.tsx
src/renderer/src/modules/feed-column/category.tsx
src/renderer/src/modules/feed-column/item.tsx
src/renderer/src/modules/feed-column/list.tsx
src/renderer/src/store/entry/helper.ts
src/renderer/src/store/entry/hooks.ts
src/renderer/src/store/entry/types.ts
src/renderer/src/store/feed/hooks.ts
src/renderer/src/store/subscription.ts

Refactored the logic for reorganizing GroupCategory data.
Modified the URL State when a Category exists, and reduced the length.
Removed the mark read action for Entry of Star.

refactor: grouped subscription folder

---

package.json
pnpm-lock.yaml
src/renderer/src/atoms/settings/general.ts
src/renderer/src/modules/entry-column/helper.ts
src/renderer/src/modules/entry-column/index.tsx
src/renderer/src/modules/entry-column/item.tsx
src/renderer/src/modules/settings/control.tsx
src/renderer/src/modules/settings/tabs/general.tsx
src/renderer/src/store/entry/store.ts

Refactor:
Use `@yornaath/batshit` to batch request

feat: mark read when hovering

---

src/main/index.ts
src/renderer/src/global.d.ts
src/renderer/src/hooks/biz/useNavigateEntry.ts
src/renderer/src/hooks/biz/useSubscriptionActions.tsx
src/renderer/src/modules/entry-column/hooks.ts
src/renderer/src/modules/entry-column/list-item-template.tsx
src/renderer/src/store/entry/store.ts
src/renderer/src/store/entry/types.ts
src/renderer/src/store/subscription/hooks.ts
src/renderer/src/store/subscription/index.ts
src/renderer/src/store/subscription/store.ts
src/renderer/src/store/utils/helper.ts
tsconfig.web.json

This refactoring:
- Started migrating MutationFunction to store action, call store action in useMutate, handle optimistic update and rollback logic in store action. (currently handles unfollow mutation), and fixes the fact that entry column data is not updated after unfollow.
* Future: migrate all mutationFn.
- The front-end handles the data sorting logic for the entry column, and now the front-end has the ability to sort the overall data in the time dimension to maintain consistency in the back-end. （Now the front-end has the ability to sort the overall data in time dimension to maintain consistency in the back-end.)

refactor: subscription store and fix unfollow data update

---

pnpm-lock.yaml
src/main/tipc.ts
src/main/window.ts
src/renderer/src/App.tsx
src/renderer/src/main.tsx

feat: Windows custom title bar

---

src/main/tipc.ts
src/renderer/src/hooks/common/useDark.ts
src/renderer/src/modules/settings/tabs/apperance.tsx

Fixed the inability to switch colors in webapps, compatible with electron's logic for switching colors.

fix: web app dark mode

---

src/renderer/src/hooks/biz/useSubscriptionActions.tsx
src/renderer/src/modules/feed-column/category.tsx
src/renderer/src/modules/feed-column/list.tsx
src/renderer/src/services/subscription.ts
src/renderer/src/store/search/index.ts
src/renderer/src/store/search/types.ts
src/renderer/src/store/subscription/hooks.ts
src/renderer/src/store/subscription/store.ts

Fix: https://discord.com/channels/1243823539426033696/1243823761913020458/1262698435916726355

fix: group category

---

src/renderer/src/components/ui/modal/stacked/context.tsx
src/renderer/src/components/ui/modal/stacked/modal.tsx
src/renderer/src/components/ui/modal/stacked/types.tsx
src/renderer/src/components/user-button.tsx
src/renderer/src/modules/auth/LoginModalContent.tsx
src/renderer/src/modules/claim/feed-claim-modal.tsx
src/renderer/src/modules/discover/content-components.tsx
src/renderer/src/modules/discover/feed-form.tsx
src/renderer/src/modules/feed-column/category-rename-dialog.tsx
src/renderer/src/modules/feed-column/category.tsx
src/renderer/src/pages/(main)/layout.tsx

Added `setClickOutSideToDismiss` when the following is available:
When Input has input
When ActionMutation is Pending

feat: add modal dismiss setter

---

src/renderer/src/pages/(external)/redirect.tsx

Hope this can open app from iPhone Safari.
https://stackoverflow.com/q/20696041/15548365

fix: use target="_top"

---

.github/workflows/build.yml

Only files selected as in screenshot are necessary?

build: remove uncessary files

---

src/renderer/src/constants/copy.ts
src/renderer/src/constants/shortcuts.ts
src/renderer/src/modules/search/cmdk.tsx
src/renderer/src/modules/settings/action-card.tsx
src/renderer/src/modules/settings/tabs/about.tsx
src/renderer/src/modules/settings/tabs/apperance.tsx
src/renderer/src/modules/settings/tabs/general.tsx

chore(settings): get rid of grammars and typos

---

src/renderer/src/modules/settings/control.tsx

https://github.com/user-attachments/assets/40514114-b613-4204-bac7-4ae86253ee6a

fix: allow toggle switch by clicking label

---

src/renderer/src/lib/query-client.ts

queryIsReadyForPersistance -> queryIsReadyForPersistence

chore: fix variable typo

---

package.json
pnpm-lock.yaml
src/hono.ts
src/renderer/src/modules/entry-column/date-item.tsx
src/renderer/src/modules/entry-column/hooks.ts
src/renderer/src/modules/entry-column/index.tsx
src/renderer/src/modules/entry-column/mark-all-button.tsx
src/renderer/src/modules/entry-column/social-media-item.tsx
src/renderer/src/modules/settings/tabs/wallet/my-wallet-section/claim-daily-reward.tsx
src/renderer/src/queries/wallet.ts
src/renderer/src/store/entry/hooks.ts
src/renderer/src/store/entry/store.ts
src/renderer/src/store/subscription/hooks.ts
src/renderer/src/store/subscription/store.ts

Organize entries by date for the following purposes:
- Establish the foundation for a future AI daily report feature, which will be displayed by date.
- Reduce users' psychological burden from information overload through segmentation.
- Allow users to mark entries as read by date, making it easier for those who only want to view the AI daily report.

feat: date item in entry column

---

forge.config.ts

Reduce macOS Electron Framework size ~40M
Before:
After:

fix: reduce Electron framework size

---

package.json
pnpm-lock.yaml
src/renderer/src/components/common/ShadowDOM.tsx
src/renderer/src/components/ui/markdown/Markdown.tsx
src/renderer/src/components/ui/markdown/context.tsx
src/renderer/src/components/ui/markdown/renderers/Heading.tsx
src/renderer/src/components/ui/media/preview-media.tsx
src/renderer/src/components/ui/modal/stacked/overlay.tsx
src/renderer/src/lib/parse-html.ts
src/renderer/src/modules/entry-content/index.tsx
vite.config.ts

Use ShadowDOM to isolate styles and implement inline newsletter styles.

feat: parse newsletter embedded `<style/>`

---

src/renderer/src/pages/(external)/login.tsx

fix: allow logout on login page

---

CHANGELOG.md
package.json
src/renderer/src/components/ui/select.tsx
src/renderer/src/hooks/common/useDark.ts
src/renderer/src/modules/entry-content/index.tsx
src/renderer/src/modules/settings/tabs/invitations.tsx

chore: Release v0.0.1-alpha.9

---

src/renderer/src/modules/settings/tabs/wallet/my-wallet-section/index.tsx

Add missing space between words

fix(wallet): add missing space between words in wallet

---

README.md

docs: follow-bin has merged into follow-appimage

---

src/renderer/src/modules/feed-column/corner-player.tsx

Fix https://github.com/RSSNext/Follow/issues/289

fix: align end for corner button in player

---

src/hono.ts
src/renderer/src/modules/discover/feed-form.tsx
src/renderer/src/modules/entry-column/templates/grid-item-template.tsx
src/renderer/src/modules/entry-column/templates/list-item-template.tsx
src/renderer/src/modules/entry-content/index.tsx
src/renderer/src/modules/feed-column/item.tsx
src/renderer/src/store/feed/hooks.ts
src/renderer/src/store/feed/store.ts

Fixes #237
Fixes FOL-34
https://github.com/RSSNext/follow-server/pull/72

feat: custom feed title

---

src/main/window.ts

当处于全屏状态时，隐藏窗口前退出全屏状态，避免产生黑屏
#339

fix: exit full screen before hiding window

---

src/renderer/src/components/ui/media/VideoPlayer.tsx
src/renderer/src/components/ui/media/preview-media.tsx

fix: style

---

src/renderer/src/modules/entry-column/translation.tsx

fix: handle empty title in entry translation

---

src/renderer/src/constants/shortcuts.ts
src/renderer/src/pages/(main)/layout.tsx
src/renderer/src/pages/settings/(settings)/shortcuts.tsx

Fixes #357 
Fixes https://linear.app/follow-app/issue/FOL-116/add-a-shortcut-reference-view

feat: shortcut h to show shortcuts modal

---

src/renderer/src/pages/(external)/(with-layout)/profile/[id]/index.tsx

change the text in the button
it should be "Edit" when i check the profile page of myself
before
after

feat: show edit when self

---

src/renderer/src/modules/modal/shortcuts.tsx
src/renderer/src/pages/settings/(settings)/shortcuts.tsx

click the button and all the row shake due to the border change
so i fixed the row height

fix: shortcuts kbd shake

---

locales/external/en.json
locales/external/fr.json
locales/external/ja.json
locales/external/pt.json
locales/external/zh-CN.json
locales/external/zh-TW.json
src/renderer/src/pages/(external)/(with-layout)/feed/[id]/index.tsx

Corrent `follows` to `followers`

fix: correct follower word

---

CHANGELOG.md
locales/app/en.json
package.json
src/main/tipc/app.ts
src/renderer/src/atoms/lang.ts
src/renderer/src/lib/load-language.ts
src/renderer/src/modules/settings/tabs/general.tsx
src/renderer/src/providers/root-providers.tsx
src/renderer/src/providers/setting-sync.tsx

chore: Release v0.0.1-alpha.13

---

.github/workflows/build.yml

Add [artifact attestations](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds#about-artifact-attestations) for releases.
Example [workflow run](https://github.com/TonyRL/Follow/actions/runs/10884672953). Example [attestations](https://github.com/TonyRL/Follow/attestations).
N/A

ci: add artifact attestation

---

src/renderer/src/components/feed-icon.tsx
src/renderer/src/components/site-icon.tsx
src/renderer/src/components/ui/list-item-hover-overlay.tsx
src/renderer/src/components/ui/media.tsx
src/renderer/src/components/ui/media/preview-media.tsx
src/renderer/src/lib/img-proxy.ts
src/renderer/src/lib/parsers.ts
src/renderer/src/modules/entry-column/Items/social-media-item.tsx
src/renderer/src/modules/entry-column/components/DateItem.tsx

Thanks and implement @hwangdev97 design.
https://www.figma.com/design/Muc8xSE4cCuFjS8CsCRaV7/Follow-timeline?node-id=10-395&node-type=frame&t=ms2tvO5MqigOe9P3-0
https://github.com/user-attachments/assets/5c31b72f-4ce7-4bdc-855c-864b7bfd3262

feat(ui): social media ui refresh

---

apps/renderer/src/modules/profile/profile-setting-form.tsx

feat: show reasons for profile update failure

---

apps/renderer/src/modules/settings/modal/content.tsx
locales/common/ar-DZ.json
locales/common/ar-MA.json
locales/common/ar-SA.json
locales/common/en.json
locales/common/es.json
locales/common/fr.json
locales/common/ja.json
locales/common/pt.json
locales/common/zh-CN.json
locales/common/zh-TW.json

The close button is too small to interact. This PR enlarges the interactive area.

feat: enlarge the interactive area of the close button

---

apps/renderer/src/modules/settings/modal/content.tsx
apps/renderer/src/modules/settings/tabs/general.tsx
locales/settings/en.json
locales/settings/zh-CN.json
locales/settings/zh-HK.json
locales/settings/zh-TW.json

fix(i18n): give star

---

apps/renderer/src/atoms/settings/ui.ts
apps/renderer/src/components/ui/code-highlighter/shiki/Shiki.tsx
apps/renderer/src/modules/settings/tabs/apperance.tsx
locales/settings/en.json
packages/shared/src/interface/settings.ts

feat: dual code theme

---

packages/shared/src/electron.ts

chore(electron): remove unless async

---

apps/renderer/src/modules/settings/tabs/lists.tsx

Add title field required
https://github.com/RSSNext/Follow/issues/565
Only one cline hange

fix: require title for list form

---

apps/renderer/src/modules/entry-column/hooks.ts
apps/renderer/src/queries/entries.ts
apps/renderer/src/store/subscription/store.ts

fix: use insertedAt as cursor for list

---

apps/renderer/src/modules/settings/modal/content.tsx

- Change viewportClassName from 'pr-1' to 'px-1'
- Ensures input is fully visible when focused
| Befor | After |
| ----- | ----- |
|  ![image](https://github.com/user-attachments/assets/74103b21-ff60-443f-8836-dd968676c372)     |    ![image](https://github.com/user-attachments/assets/96684890-df53-4dc5-9796-2dd717c17bae)   |

fix: improve input component display on focus

---

apps/renderer/src/modules/settings/tabs/lists.tsx

list manage Modal zh-cn word warp

fix: list manage Modal button zh-cn word wrap

---

locales/app/zh-CN.json

Change "核心玩家" to "硬核玩家"，"Hardcore" should be translated to "硬核".

Correction of zh-CN translation

---

apps/renderer/src/components/ui/media.tsx

https://discord.com/channels/1243823539426033696/1243823761913020458/1288123303789072467

fix: show fallback media when loading error

---

apps/renderer/src/modules/feed-column/corner-player.tsx

fix(corner-player): pause playback when player finishes

---

apps/renderer/src/modules/entry-content/components/EntryTitle.tsx
apps/renderer/src/modules/entry-content/components/SupportCreator.tsx
apps/renderer/src/modules/entry-content/index.tsx

This pull request refactors the `EntryContent` component by extracting new components. 
This modularization improves code readability and maintainability.

refactor: extract component from EntryContent

---

apps/renderer/src/lib/environment.ts
apps/renderer/src/lib/issues.ts
apps/renderer/src/modules/settings/tabs/about.tsx

Copy your environment
Copy result: 
```
**App Version**: 0.0.1-alpha.17
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
**Env**: web
**Browser**: Chrome
```

feat(about): copy your environment

---

apps/renderer/src/modules/entry-column/Items/picture-item.tsx

[29f2c0c](https://github.com/RSSNext/Follow/commit/29f2c0ca41badb34b001ac9dff91c1e2b600a71f) only work in Pictures View's Masonry view now, but not work in Grid view.
#652

fix: picture entry preview in Grid view

---

apps/renderer/src/components/feed-summary.tsx

fix: add truncate class to feed link

---

locales/app/zh-CN.json

chinese translation: context menu of adding feeds to lists

feat(i18n): zh-CN: context menu of adding feeds to lists

---

apps/renderer/src/modules/entry-column/Items/video-item.tsx

fix: add rounded class to video fallback message

---

apps/renderer/src/components/ui/markdown/Markdown.tsx
apps/renderer/src/components/ui/markdown/renderers/BlockImage.tsx
apps/renderer/src/components/ui/media.tsx
apps/renderer/src/lib/parse-html.ts
apps/renderer/src/modules/entry-content/index.tsx

https://github.com/user-attachments/assets/1680f905-b715-410d-b5a9-09b09fb7524a

fix: avoid image cls in entry content

---

apps/renderer/src/components/ui/code-highlighter/shiki/Shiki.tsx
apps/renderer/src/components/ui/code-highlighter/shiki/shiki.module.css
apps/renderer/src/lib/parse-html.ts
apps/renderer/src/modules/entry-content/index.tsx

Fix the `Cannot use 'in' operator to search for 'type' in undefined` introduced in ab8c9e5.
Feed: https://dmesg.app/workers-function.html in https://dmesg.app/feed
#640

fix: null reference introduced in ab8c9e5

---

apps/renderer/src/pages/(main)/layout.tsx

Improved the text in `apps/renderer/src/pages/(main)/layout.tsx` for better readability and grammar.
No related issues found.
I did not find related strings in the `locale` folder, indicating that this section is not internationalized. This will not be addressed in this pull request.

fix(i18n/en): enhance English grammar

---

apps/renderer/src/modules/entry-content/components/EntryReadHistory.tsx

More natural animation effects when hovering over the mouse
**Old**
**New**

chore(transition): apply natural transition for avatar dropdown

---

apps/renderer/src/components/ui/modal/stacked/modal.tsx
apps/renderer/src/modules/settings/modal/layout.tsx

Before:
https://github.com/user-attachments/assets/1fcda12c-b3ce-491a-b35e-644ceb95aa65
After:
https://github.com/user-attachments/assets/1763451f-94ad-4a53-9965-2487373811fa

fix(modal): limit setting modal drag range

---

apps/renderer/src/modules/settings/modal/layout.tsx
apps/renderer/src/modules/settings/title.tsx

fix: setting modal's edge round is covered by content background

---

apps/renderer/src/components/ui/media/preview-media.tsx

before:
https://github.com/user-attachments/assets/9d577b07-af3a-4caa-8196-f0cc1c0a066d
after:
https://github.com/user-attachments/assets/6c2aa127-47e3-461e-b9a9-c884988e50c9

fix: enable pointer events for action buttons in media preview

---

apps/renderer/src/modules/auth/LoginModalContent.tsx

refactor: delete redundant types

---

apps/renderer/src/components/ui/context-menu/context-menu.tsx
apps/renderer/src/hooks/biz/useFeedActions.tsx
apps/renderer/src/lib/native-menu.ts
apps/renderer/src/modules/entry-column/item.tsx
apps/renderer/src/modules/entry-column/layouts/EntryItemWrapper.tsx
apps/renderer/src/modules/entry-column/layouts/EntryListHeader.tsx
apps/renderer/src/modules/feed-column/category.tsx
apps/renderer/src/modules/feed-column/index.tsx
apps/renderer/src/modules/feed-column/item.tsx
apps/renderer/src/modules/feed-column/list.tsx
apps/renderer/src/modules/feed-column/styles.ts
apps/renderer/src/modules/settings/modal/layout.tsx
apps/renderer/src/modules/settings/tabs/invitations.tsx
apps/renderer/src/modules/settings/tabs/lists.tsx
apps/renderer/src/modules/settings/tabs/lists/index.tsx
apps/renderer/src/modules/settings/tabs/lists/modals.tsx
apps/renderer/src/pages/(external)/redirect.tsx
apps/renderer/src/pages/settings/(settings)/actions.tsx
apps/renderer/src/providers/context-menu-provider.tsx
locales/app/en.json
locales/app/zh-CN.json
locales/app/zh-HK.json
locales/app/zh-TW.json
locales/settings/zh-CN.json

- feat: disabled when exceed invite limitation
- feat: add item hover
- fix: create list minimum value is 0
- feat: add actions settings loading
- feat: hide menu when enabled is false
- feat: change opacity when menu is disabled
- feat: add quick access for add feed to list
中文：
- feat: 邀请数量达到上限时禁用「生成邀请码」按钮
- feat: 增加订阅源列表hover和设置面板标签hover
- fix: 订阅列表花费积分最小为0
- feat: 增加自动化设置面板加载态
- feat: 当菜单属性enabled为false时隐藏菜单选项（比如分享列表为空）
- feat: 当菜单disabled为true时展示选项禁用态
- feat: 增加菜单「创建列表」快捷入口

feat(ui): enhance context menu with hover effects, disable option, and quick list creation

---

apps/renderer/src/models/types.ts
apps/renderer/src/modules/settings/action-card.tsx
locales/settings/en.json
packages/shared/src/hono.ts

- close #627
- https://github.com/RSSNext/follow-server/pull/115

feat: silence action

---

apps/renderer/src/lib/parse-html.ts

Social View, In `parseHtml` function, `noMedia` convert a tree `['p', 'p', 'br', 'img', 'br', 'img', 'br']` to `['p', 'p', 'br', 'br', 'br']`, which is ugly when rendered.
So I trim all trailing br elements.
Feed: rsshub://jike/user/752D3103-1107-43A0-BA49-20EC29D09E36

feat: trim social media view end redundant br elements

---

apps/main/src/lib/context-menu.ts
apps/renderer/src/modules/settings/action-card.tsx

fix: improve ActionCard state management and UI

---

apps/renderer/src/lib/native-menu.ts

This PR removes empty menu items from native menu

fix: hidden menu item is not filtered out on native

---

apps/renderer/src/atoms/player.ts
apps/renderer/src/hooks/biz/useNavigateEntry.ts
apps/renderer/src/modules/feed-column/corner-player.tsx
apps/renderer/src/store/entry/types.ts

This PR optimizes the navigation from the TTS player, includes:
https://github.com/user-attachments/assets/9447dc0d-6ed0-4f29-9382-fd1a2b6ac8c2
https://github.com/user-attachments/assets/468581d9-5851-437d-9e46-0b02304710e4
(Updated)

fix: navigating from a tts player doesn't work properly

---

apps/renderer/src/modules/panel/cmdf.tsx

set cmdf container `z-index` to `1000`.
result

fix: set cmdf container `z-index` to `1000`

---

apps/renderer/src/modules/panel/cmdk.tsx

fix `cmdk` panel footer layout.
fixed the `ScrollArea` area and changed some spacing.
result

fix: cmdk panel layout

---

locales/common/zh-CN.json
locales/settings/zh-CN.json

i18n: tx types filter
i18n: delete list

chore(i18n): Chinese: add some word

---

apps/main/src/lib/dock.ts

refactor(dock): simplify badge count logic

---

apps/renderer/src/components/ui/auto-completion/AutoCompletion.tsx

fix: turn off native form autocompletion in `AutoCompletion`

---

forge.config.ts

Now: 
Before:
Close: https://discord.com/channels/1243823539426033696/1294232031148118088

fix: app icon incorrect in Windows Control Panel

---

apps/renderer/src/modules/user/ProfileButton.tsx

fix: update DropdownMenuTrigger class for open state styling

---

.github/workflows/build.yml
.github/workflows/nightly.yml

error message:
```
node_modules/macos-alias install: Traceback (most recent call last):
node_modules/macos-alias install:   File "/Users/runner/work/Follow/Follow/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
node_modules/macos-alias install:     import gyp  # noqa: E402
node_modules/macos-alias install:     ^^^^^^^^^^
node_modules/macos-alias install:   File "/Users/runner/work/Follow/Follow/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
node_modules/macos-alias install:     import gyp.input
node_modules/macos-alias install:   File "/Users/runner/work/Follow/Follow/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
node_modules/macos-alias install:     from distutils.version import StrictVersion
node_modules/macos-alias install: …
```

fix(ci): cannot release macOS APP

---

apps/renderer/src/hooks/biz/useFeedActions.tsx
apps/renderer/src/lib/native-menu.ts
apps/renderer/src/modules/feed-column/category.tsx

Refactor useFeedActions component to conditionally add a separator in the menu list based on the length of listByView array.
Refactor FeedCategoryImpl component to conditionally add a separator in the menu list based on the length of listList array.

Refactor useFeedActions component to conditionally add a separator

---

locales/settings/ar-DZ.json
locales/settings/ar-IQ.json
locales/settings/ar-KW.json
locales/settings/ar-MA.json
locales/settings/ar-SA.json
locales/settings/ar-TN.json
locales/settings/de.json
locales/settings/en.json
locales/settings/es.json
locales/settings/fi.json
locales/settings/fr.json
locales/settings/it.json
locales/settings/ja.json
locales/settings/ko.json
locales/settings/pt.json
locales/settings/ru.json
locales/settings/tr.json

I found a 'repeat value' issue in the i18n for all languages except Simplified and Traditional Chinese.
But none of the Chinese languages have this issue
I have fixed this issue.

fix(i18n): repeat value

---

apps/renderer/src/modules/settings/tabs/lists/modals.tsx

fix: correct method call for <a> tag in Manage Feeds within Lists

fix: correct method call for <a> tag in Manage Feeds within Lists

---

apps/renderer/src/components/ui/scroll-area/ScrollArea.tsx
apps/renderer/src/modules/trending/index.tsx

https://github.com/RSSNext/Follow/commit/3edee63a5a9f691481c8532ba524d541ca09c539#diff-2bd15723d33f49ade6aaf527ddfd0549ae37e38e6c5d456e4b88cb6da91c3415R142
This code seems lost. It makes the below problem.

fix: trending drawer overflow

---

apps/renderer/src/modules/entry-content/components/EntryReadHistory.tsx
apps/renderer/src/modules/entry-content/header.tsx

1. Avatar display problem in wideMode
2. Reading history not shown for first time in non-article types
close #860

fix: read history not showing, adjust limit based on view

---

apps/renderer/src/modules/discover/inbox-list-form.tsx

refered to the loading style of the RSS3, User, and Transform modules in Discover

feat: add loading when Discover Inbox querying data

---

apps/renderer/src/components/ui/media/preview-media.tsx

fix: can't see ActionButton well in light theme

---

apps/renderer/src/modules/settings/tabs/about.tsx

Before
https://github.com/user-attachments/assets/84908402-5ef3-464d-8e32-d66f7f2f59d0
After
https://github.com/user-attachments/assets/04258300-2ffa-4acd-9150-a604025b9c83

fix: optimize about share btn padding

---

README.md

Add a new method for installing via Homebrew in `README.md`

docs: adding a new method for installing via Homebrew

---

apps/renderer/src/modules/settings/sections/fonts.tsx

Add an option to use system-ui font on desktop app

feat: add system-ui font selection to desktop app

---

apps/renderer/src/modules/achievement/AchievementModalContent.tsx

When the height is insufficient, the achievement list cannot be fully displayed.
before
after

fix: solve overflow issue in achievement model

---

apps/renderer/src/modules/profile/hooks.ts

fix(modal): repeat user profile dialog

---

apps/renderer/src/modules/profile/user-profile-modal.tsx

There have some shaking animation of the Follow button on the User Profile Modal
**before**
https://github.com/user-attachments/assets/de11d976-2c18-4eba-989c-d088afe95ae4
**after**
https://github.com/user-attachments/assets/aa691eaf-7f5a-47d5-98ad-5047ed195963

fix: optimize the animation of the Follow button on the User Profile Modal

---

apps/renderer/src/modules/settings/tabs/apperance.tsx
packages/hooks/src/useSyncTheme.ts

The client version theme cannot be switched.
before
https://github.com/user-attachments/assets/a5e37517-7f72-4bc3-a1e9-40b892f03f17
after
https://github.com/user-attachments/assets/bf53b80c-59fe-40fc-af65-f9599a22d016

fix: theme cannot be switched

---

apps/renderer/src/modules/feed-column/index.tsx
apps/renderer/src/modules/feed-column/item.tsx
apps/renderer/src/modules/feed-column/list.tsx

perf: resolve feed item select area performance problem

---

README.md

Update information about installing via Homebrew in README.md

docs: update Homebrew casks

---

apps/renderer/src/modules/achievement/AchievementModalContent.tsx

chore: typo

---

apps/renderer/src/modules/discover/feed-form.tsx

fix: modal bottom buttons align

---

apps/renderer/src/modules/settings/tabs/lists/index.tsx

fix: show scrollbar when list table overflows in settings menu

---

forge.config.ts
package.json
pnpm-lock.yaml
scripts/merge-yml.ts

Separate packaging for macOS x64 and arm64 architectures
#1388

feat: separate packaging for macOS x64 and arm64 architectures

---

apps/renderer/src/modules/power/my-wallet-section/withdraw.tsx

Added check in onSubmit to prevent withdrawal if amount is zero
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/RSSNext/Follow?shareId=789051f6-2228-4c4f-ac48-a593d371605d).

fix: prevent withdrawal of zero amount to avoid unnecessary fees

---

apps/renderer/src/modules/settings/title.tsx

when open settings modal ⬇️
refer to: 
https://github.com/RSSNext/Follow/commit/d0d4f0564715c1786e71b0f009e86aa3a9dc4b7c
https://github.com/RSSNext/Follow/commit/da8aad7327d45cd899f8091cb0315ff2497b2ab9

fix: setting loader type error

---

apps/main/src/helper.ts
apps/main/src/index.ts
apps/main/src/lib/tray.ts

Adjust the tray icon path for Windows and improve the behavior of the main window when it is focused.

fix: update tray icon path for windows and improve window focus behavior

---

apps/main/src/helper.ts
apps/main/src/index.ts
apps/main/src/lib/tray.ts
apps/renderer/src/hooks/biz/useSignOut.ts
apps/renderer/src/modules/feed-column/list.tsx
apps/renderer/src/pages/(main)/layout.tsx
apps/renderer/src/queries/auth.ts
bump.hotfix.config.js
changelog/0.2.0-beta.1.md
package.json

chore: Release v0.2.0-beta.1 hotfix

---

apps/renderer/src/providers/context-menu-provider.tsx

prevent right cilck on content menu

fix: prevent right cilck on content menu

---

apps/renderer/src/modules/settings/modal/layout.tsx

chore(ui/settings): prevent ui text from being selected

---

apps/renderer/src/modules/command/commands/integration.tsx

Add dependencies to various command registration hooks to ensure proper functionality based on availability checks.

fix: add deps for integration cmds

---

apps/renderer/src/hooks/biz/useEntryActions.tsx
apps/renderer/src/hooks/biz/useFeedActions.tsx
apps/renderer/src/modules/claim/hooks.ts
apps/renderer/src/modules/entry-column/layouts/EntryItemWrapper.tsx
apps/renderer/src/modules/feed-column/atom.ts
apps/renderer/src/modules/feed-column/category.tsx
apps/renderer/src/modules/feed-column/index.tsx
apps/renderer/src/modules/feed-column/item.tsx
apps/renderer/src/modules/feed-column/list.tsx
apps/renderer/src/modules/wallet/tip-modal.tsx
apps/renderer/src/queries/feed.ts

Refactor components to enhance performance through memoization and improved state management.
Adjustments include changes to feed actions and modal handling, resulting in a more efficient rendering process.

fix: improve perform for feed column

---

apps/renderer/src/modules/power/ranking/index.tsx
apps/renderer/src/modules/power/transaction-section/tx-table.shared.tsx
apps/renderer/src/modules/profile/user-profile-modal.shared.tsx
apps/renderer/src/modules/settings/tabs/invitations.tsx

Fix undefined image prop when clicking user image on the power page

fix: replace Avatar component with UserAvatar in ranking and transaction sections

---

apps/renderer/src/modules/activation/ActivationModalContent.tsx

Current version
After modification
#1234

fix: change invitation code placeholder font to theme font

---

.npmrc
apps/main/package.json
package.json
packages/shared/package.json
pnpm-lock.yaml

Upstream https://github.com/electron/electron/issues/44898
Thanks to @ericyzhu!

fix: revert electron bump

---

apps/main/src/lib/download.ts
apps/renderer/src/components/ui/code-highlighter/shiki/shiki.module.css
apps/renderer/src/components/ux/pull-to-refresh/index.tsx
plugins/eslint/eslint-check-i18n-json.js

Make code comments are in consistence with language, so as to make the code cleaner.

typo: make code comments are in consistence with language.

---

apps/main/package.json
apps/server/package.json
pnpm-lock.yaml

Fix https://app.follow.is/share/feeds/89647144094736384
See https://github.com/WebReflection/linkedom/pull/293 for more details.

fix: unexpected hydrate unmatched

---

apps/renderer/src/components/ui/fab/FABContainer.tsx

Before:
https://github.com/user-attachments/assets/87b4dd57-f0dd-4e66-8545-3fe31b2a0802
After:
https://github.com/user-attachments/assets/568228a0-5389-437b-8b27-2756bd926a57

fix: flickering issue when FAB button disappears

---

apps/renderer/src/modules/power/my-wallet-section/claim-daily-reward.tsx
apps/renderer/src/modules/power/ranking/index.tsx

fix: console error in power page

---

.vscode/settings.json

css file associations
before:  
after:

chore: `files.associations` settings for vscode

---

apps/renderer/src/modules/entry-content/index.mobile.tsx

prevent unnecessary navigate
#2133

fix: view freeze while using swipe gesture to go back in safari

---

tailwind.config.ts

As shown in the screenshot
https://tailwindcss.com/docs/content-configuration#pattern-recommendations
https://github.com/tailwindlabs/tailwindcss/discussions/12892

fix: exclude node_modules from Tailwind scanning

---

apps/renderer/src/modules/profile/email-management.tsx

feat: improve email verification display

---

apps/renderer/src/modules/power/transaction-section/index.tsx
apps/renderer/src/modules/power/transaction-section/tx-table.mobile.tsx
apps/renderer/src/modules/power/transaction-section/tx-table.shared.tsx

https://github.com/user-attachments/assets/03111854-38a7-4803-8b53-ffdb3c363dfd

feat: add loading indicator and UI improvements in transaction

---

apps/renderer/src/modules/player/corner-player.tsx

fix(mobile): improve responsive design in CornerPlayer

---

apps/renderer/src/modules/app-layout/feed-column/components/PodcastButton.tsx
apps/renderer/src/modules/app-layout/feed-column/float-bar.mobile.tsx
apps/renderer/src/modules/player/corner-player.tsx

Close: #2432
<details>
<summary>Before:</summary>
https://github.com/user-attachments/assets/7dbe3831-98a1-4fff-b8d1-deaa86b0fe45
</details>
After:
https://github.com/user-attachments/assets/60155c44-2f1f-4fec-8e06-891fb8bf5d83

feat(mobile): improve podcast player

---

apps/renderer/src/hooks/biz/useEntryActions.tsx
apps/renderer/src/modules/entry-column/Items/social-media-item.tsx
apps/renderer/src/modules/entry-column/layouts/EntryItemWrapper.tsx
apps/renderer/src/modules/entry-column/list.tsx
apps/renderer/src/modules/entry-content/actions/header-actions.tsx
apps/renderer/src/modules/entry-content/actions/more-actions.tsx
apps/renderer/src/modules/entry-content/header.mobile.tsx
locales/settings/zh-CN.json

Replace direct usage of entry actions with a new hook that sorts actions into main and more categories, improving organization and maintainability.

refactor: update header action

---

apps/renderer/src/components/ui/button/CommandActionButton.tsx
apps/renderer/src/modules/entry-column/grid.tsx

fix: warning and error in console

---

apps/renderer/src/modules/entry-column/list.tsx

Rename functions related to sticky item checks for improved readability and understanding.
https://github.com/user-attachments/assets/eaf427e0-0d31-49e2-97c6-04d3a31b3e1b

refactor: tweak sticky item for simplify the logic

---

apps/renderer/src/pages/settings/(settings)/profile.tsx

refactor(profile): unify with other pages

---

apps/renderer/src/modules/entry-content/index.mobile.tsx
locales/settings/zh-CN.json

feat: apply custom css to mobile

---

apps/mobile/src/lib/platform.ts
apps/mobile/src/modules/feed-drawer/collection-panel.tsx
apps/mobile/src/modules/subscription/items/SubscriptionItem.tsx

Update styles of the feed item
Related to https://github.com/RSSNext/Follow/commit/2edebdfcdb7af277b19454551729e30f5cfa46ce

chore: tweak styles of feed item

---

apps/renderer/src/lib/load-language.ts

Fix https://github.com/RSSNext/Follow/pull/2558

fix: dispatch I18N_UPDATE event after language load

---

apps/renderer/src/pages/(main)/(layer)/(subview)/discover/index.tsx

fix: update ScrollArea className for better width handling

---

apps/renderer/src/modules/feed-column/list.shared.tsx

fix(feed-column): correct sorting icon status

---

apps/mobile/src/contexts/LoginTeamsContext.tsx
apps/mobile/src/contexts/LoginTermsContext.tsx
apps/mobile/src/modules/login/email.tsx
apps/mobile/src/modules/login/index.tsx
apps/mobile/src/modules/login/social.tsx
apps/mobile/src/screens/(headless)/terms.tsx
pnpm-lock.yaml

Enhance the user interface for the login terms on mobile
Fix typo 'team' -> 'term'

chore(mobile): improve layout and styling in login terms

---

apps/mobile/app.config.ts
apps/mobile/scripts/with-follow-assets.js
apps/mobile/src/components/common/FollowWebView.tsx

Improve asset handling by updating the configuration and scripts to dynamically manage asset paths, ensuring assets are correctly copied to the app bundle.
Mark the old WebView component as deprecated.

refactor: update asset handling in mobile app

---

apps/mobile/drizzle/0008_last_the_santerians.sql
apps/mobile/drizzle/meta/0008_snapshot.json
apps/mobile/drizzle/meta/_journal.json
apps/mobile/drizzle/migrations.js
apps/mobile/src/database/schemas/index.ts
apps/mobile/src/database/schemas/types.ts
apps/mobile/src/modules/context-menu/entry.tsx
apps/mobile/src/morph/hono.ts
apps/mobile/src/services/collection.ts
apps/mobile/src/services/index.ts
apps/mobile/src/store/collection/hooks.ts
apps/mobile/src/store/collection/store.ts
apps/mobile/src/store/collection/types.ts
apps/mobile/src/store/entry/store.ts
apps/mobile/src/store/entry/types.ts

Introduce a new collections table and provide services for managing collections, including starring and unstarring entries.
Update relevant hooks and store actions to support collection functionality.

feat: add collections table and implement collection management services

---

apps/renderer/src/modules/entry-column/Items/article-item.tsx
apps/renderer/src/modules/entry-column/Items/audio-item.tsx
apps/renderer/src/modules/entry-column/templates/list-item-template.tsx

refactor: merge audio item

---

apps/mobile/src/modules/entry-list/entry-list-gird.tsx
apps/mobile/src/modules/entry-list/entry-list.tsx
apps/mobile/src/store/entry/hooks.ts

feat(mobile): refresh control for entry list

---

apps/mobile/src/modules/context-menu/entry.tsx

This pull request includes changes to the `context-menu/entry.tsx` file to improve the handling of starring and unstarring entries.

fix(mobile): update types and star entry with view

---

apps/renderer/src/modules/entry-column/Items/article-item.tsx
apps/renderer/src/modules/entry-column/Items/audio-item.tsx
apps/renderer/src/modules/entry-column/templates/list-item-template.tsx

revert: Revert "refactor: merge audio item"

---

apps/mobile/src/components/ui/datetime/RelativeDateTime.tsx
apps/mobile/src/modules/entry-list/entry-list-article.tsx
apps/mobile/src/modules/entry-list/entry-list-social.tsx

chore(mobile): display feed title in entry item

---

apps/mobile/src/constants/views.tsx
apps/mobile/src/modules/entry-list/entry-list-article.tsx
apps/mobile/src/modules/entry-list/entry-list-social.tsx

fix(mobile): unread style not working, bring views back

---

apps/renderer/src/modules/entry-content/components/EntryReadHistory.mobile.tsx

feat(mobile): add triggerAsChild prop to EntryReadHistory component

---

apps/mobile/src/modules/entry-list/entry-list-article.tsx
apps/mobile/src/modules/entry-list/entry-list-social.tsx
apps/mobile/src/modules/feed-drawer/atoms.ts
apps/mobile/src/modules/screen/TimelineSelectorHeader.tsx

fix(mobile): use the right import path for feed atom

---

apps/mobile/src/modules/entry-list/entry-list-article.tsx
apps/mobile/src/modules/entry-list/entry-list-gird.tsx
apps/mobile/src/modules/entry-list/entry-list-social.tsx
apps/mobile/src/modules/entry-list/hooks.ts
apps/mobile/src/modules/screen/TimelineSelectorList.tsx
apps/mobile/src/screens/(stack)/(tabs)/_layout.tsx
apps/mobile/src/services/unread.ts
apps/mobile/src/store/unread/store.ts

feat(mobile): auto mark as read when scrolling

---

apps/renderer/src/modules/settings/tabs/apperance.tsx
packages/components/src/ui/select/responsive.tsx

feat(select): add itemClassName prop for customizable item styling

---

apps/mobile/src/modules/entry-list/EntryListSelector.tsx
apps/mobile/src/modules/entry-list/index.tsx
apps/mobile/src/modules/entry-list/usePagerView.ts
apps/mobile/src/screens/(stack)/feeds/[feedId]/index.tsx

feat(mobile): refactor EntryList to use pager view

---

apps/mobile/scripts/with-follow-assets.js

fix: rn-micro-web-app build

---

apps/renderer/src/modules/entry-column/templates/list-item-template.tsx
package.json

- add type check for cover
- add cross-env for better windows dev experience
Before
after
Closes #2812

fix(listEntryCover): fix the cover mistakely render as audio

---

apps/renderer/src/modules/timeline-column/TimelineSelector.tsx

| Before | After |
| ---- | ----- |
|<img src="https://github.com/user-attachments/assets/a6d4775b-61a5-463e-a446-93f2538bd1cc" width="200" /> | <img src="https://github.com/user-attachments/assets/5dadff7a-3712-4e26-9825-5c935ea31871" width="150" /> |

refactor(timeline): simplify timeline view rendering

---

.github/workflows/build-eas.yml

chore: profile input

---

apps/mobile/src/atoms/scroll-to-top.ts
apps/mobile/src/components/common/SafeNavigationScrollView.tsx
apps/mobile/src/modules/entry-list/EntryListContentArticle.tsx
apps/mobile/src/modules/entry-list/EntryListContentGrid.tsx
apps/mobile/src/modules/entry-list/EntryListContentSocial.tsx
apps/mobile/src/modules/entry-list/EntryListSelector.tsx
apps/mobile/src/modules/entry-list/index.tsx
apps/mobile/src/modules/screen/TimelineSelectorList.tsx

feat(mobile): implement scroll-to-top functionality

---

apps/mobile/src/store/entry/hooks.ts
apps/mobile/src/store/entry/store.ts
apps/mobile/src/store/entry/types.ts
apps/renderer/src/modules/entry-column/hooks/useEntriesByView.ts
apps/renderer/src/modules/entry-column/index.tsx
apps/renderer/src/queries/entries.ts
apps/renderer/src/store/entry/store.ts
packages/shared/src/constants.ts

part of FOL-1626
- https://github.com/RSSNext/follow-server/pull/250

refactor(entries): remove isArchived parameter from entry fetching logic

---

apps/mobile/src/components/common/SafeNavigationScrollView.tsx
apps/mobile/src/modules/entry-list/EntryListSelector.tsx

refactor(mobile): remove legacy scroll-to-top

---

apps/mobile/src/modules/entry-list/EntryListSelector.tsx

Fix scroll to top not work when clicking tabbar
Blame to https://github.com/RSSNext/Follow/pull/2855

fix(mobile): scroll to top when clicking on the tabbar

---

apps/renderer/package.json
apps/server/package.json
changelog/next.md
packages/components/package.json
packages/utils/package.json
pnpm-lock.yaml

fix: update framer motion version

---

apps/mobile/src/components/common/SafeNavigationScrollView.tsx
apps/renderer/src/modules/auth/Form.tsx
apps/renderer/src/modules/auth/LoginModalContent.tsx

- disable the submit button when the form state is invalid
- correct tab navigation behavior
- fix form width change when submitting
#2869

fix: improve login form behavior and style

---

apps/renderer/src/modules/discover/form.tsx
locales/external/en.json
locales/external/zh-CN.json
locales/external/zh-HK.json

feat(i18n): add translation support for follow actions in discover

---

apps/mobile/src/modules/dialogs/AddFeedDialog.tsx
apps/mobile/src/modules/entry-content/EntryGridFooter.tsx

Enhance the text styling in EntryGridFooter and improve padding in the AddFeedDialog input field for better usability.

chore(mobile): improve styling

---

apps/mobile/app.config.ts

chore(mobile): disable tablet support for iOS

---

apps/mobile/src/modules/entry-list/EntryListContentArticle.tsx
apps/mobile/src/modules/entry-list/EntryListContentGrid.tsx
apps/mobile/src/modules/entry-list/EntryListContentSocial.tsx
apps/mobile/src/modules/entry-list/hooks.ts

fix(mobile): do not mark as read when scrolling up

---

apps/mobile/package.json
apps/mobile/src/initialize/hydrate.ts
apps/mobile/src/initialize/index.ts
apps/mobile/src/lib/query-client.ts
apps/mobile/src/modules/discover/Recommendations.tsx
apps/mobile/src/morph/hono.ts
apps/mobile/src/providers/index.tsx
pnpm-lock.yaml

feat(mobile): cache rsshub query

---

apps/mobile/src/screens/(headless)/login.tsx

Enhance the login page by allowing developers to redirect to the home page manually during development, while maintaining the standard login flow for production.

refactor(mobile): login page for improved development experience

---

apps/mobile/src/components/ui/carousel/MediaCarousel.tsx
apps/mobile/src/modules/entry-content/EntryGridFooter.tsx
apps/mobile/src/modules/entry-list/EntryListContentPicture.tsx
apps/mobile/src/modules/entry-list/EntryListContentVideo.tsx
apps/mobile/src/modules/entry-list/EntryListSelector.tsx
apps/mobile/src/modules/entry-list/templates/EntryGridItem.tsx
apps/mobile/src/modules/entry-list/templates/EntryPictureItem.tsx
apps/mobile/src/modules/entry-list/templates/EntryVideoItem.tsx

Improve layout for video entries, introduce new components for video content, and refactor existing components for better structure and performance.

refactor(mobile): enhance video entry handling in mobile app

---

apps/mobile/src/modules/entry-list/templates/EntrySocialItem.tsx

| Before | After |
| --- | ---- |
| <img src="https://github.com/user-attachments/assets/8b7b3be7-b1eb-49b2-b873-483545cfc4b9" width="300" /> | <img src="https://github.com/user-attachments/assets/7c737c47-95d9-4883-8beb-7312a762d789" width="300" /> |

fix(mobile): title text style in social media

---

apps/mobile/src/lib/image.ts

fix(mobile): crash when parsing invalid url

---

apps/mobile/src/components/layouts/tabbar/hooks.ts
apps/mobile/src/modules/discover/Recommendations.tsx
apps/mobile/src/modules/entry-list/EntryListSelector.tsx
apps/mobile/src/modules/screen/TimelineSelectorList.tsx
apps/mobile/src/modules/subscription/SubscriptionLists.tsx
apps/mobile/src/screens/(stack)/(tabs)/settings.tsx

Enhance type safety and improve navigation scroll view handling.
Update the content scroller reference in the discover screen to ensure proper scrolling behavior.

refactor(mobile):  improve navigation scroll view handling

---

apps/mobile/src/components/layouts/tabbar/Tabbar.tsx
apps/mobile/src/modules/player/PlayerTabBar.tsx

fix(mobile): player tab animation

---

apps/mobile/src/modules/entry-list/EntryListContentArticle.tsx
apps/mobile/src/modules/entry-list/EntryListContentPicture.tsx
apps/mobile/src/modules/entry-list/EntryListContentSocial.tsx
apps/mobile/src/modules/entry-list/EntryListContentVideo.tsx
apps/mobile/src/modules/entry-list/index.tsx

fix(mobile): active views in pager, first loading no mark read

---

apps/mobile/web-app/html-renderer/vite.config.mts

build: fix import path

---

.vscode/settings.json
eslint.config.mjs

build: fix tailwind config location

---

package.json
patches/eslint-plugin-tailwindcss.patch
pnpm-lock.yaml

build: use correct tailwind config to lint

---

apps/mobile/src/components/common/ModalSharedComponents.tsx
apps/mobile/src/hooks/useIntentHandler.ts
apps/mobile/src/screens/+native-intent.tsx
apps/mobile/src/screens/_layout.tsx

refactor(mobile): enhance deep link handling with intent hook

---

apps/mobile/src/hooks/useIntentHandler.ts
apps/mobile/src/screens/+native-intent.tsx

This pull request focusing on improving the handling of deep links and resetting intent URLs. The most important changes include adding a function to reset the intent URL, modifying the deep link extraction logic, and ensuring the intent URL is reset when redirecting system paths.

feat(mobile): add list and url support for deep link

---

apps/desktop/locales/app/zh-CN.json

Resolved #2964.
#2964
I couldn't find the `changelog/next.md` file, so I didn't make any changes.

chore(i18n): zh-CN update translation

---

apps/mobile/drizzle/0014_chemical_shocker.sql
apps/mobile/drizzle/meta/0014_snapshot.json
apps/mobile/drizzle/meta/_journal.json
apps/mobile/drizzle/migrations.js
apps/mobile/src/database/schemas/index.ts
apps/mobile/src/modules/entry-content/EntryReadHistory.tsx
apps/mobile/src/modules/entry-list/index.tsx
apps/mobile/src/modules/entry-list/templates/EntryNormalItem.tsx
apps/mobile/src/modules/screen/atoms.ts
apps/mobile/src/modules/subscription/SubscriptionLists.tsx
apps/mobile/src/modules/subscription/items/InboxItem.tsx
apps/mobile/src/modules/subscription/items/ListSubscriptionItem.tsx
apps/mobile/src/modules/subscription/items/SubscriptionItem.tsx
apps/mobile/src/modules/subscription/items/UnreadCount.tsx
apps/mobile/src/morph/hono.ts
apps/mobile/src/morph/types.ts
apps/mobile/src/screens/(stack)/feeds/[feedId]/index.tsx
apps/mobile/src/services/list.ts
apps/mobile/src/store/entry/hooks.ts
apps/mobile/src/store/entry/store.ts
apps/mobile/src/store/entry/utils.ts
apps/mobile/src/store/list/getters.ts
apps/mobile/src/store/list/hooks.ts
apps/mobile/src/store/list/store.ts
apps/mobile/src/store/subscription/getter.ts
apps/mobile/src/store/subscription/store.ts
apps/mobile/src/store/unread/hooks.ts

feat(mobile): list and inbox

---

apps/desktop/changelog/0.3.10.md
apps/desktop/package.json
apps/desktop/src/main/preload/index.ts
apps/desktop/src/renderer/src/initialize/index.ts
apps/desktop/src/renderer/src/providers/root-providers.tsx
apps/mobile/package.json
apps/mobile/src/lib/native/picker.ts
apps/mobile/src/modules/settings/routes/Account.tsx
apps/mobile/src/modules/settings/routes/EditProfile.tsx
pnpm-lock.yaml

release(desktop): Release v0.3.10

---

apps/mobile/src/screens/(modal)/login.tsx

fix(mobile): login redirect

---

apps/mobile/native/ios/FollowNative.podspec
apps/mobile/native/ios/Toaster/ToasterModule.swift
apps/mobile/src/components/native/webview/EntryContentWebView.tsx
apps/mobile/src/components/ui/toast/types.ts
apps/mobile/src/lib/toast.tsx
apps/mobile/src/modules/screen/action.tsx
apps/mobile/src/screens/(stack)/entries/[entryId]/index.tsx

fix(mobile): toast when toggling unread, fix entry context crash

---

apps/desktop/src/main/src/index.ts
apps/desktop/src/main/src/lib/tray.ts
apps/desktop/src/main/src/window.ts

fix: windows file path

---

apps/mobile/src/modules/settings/routes/Data.tsx
apps/mobile/src/modules/settings/utils.ts

Extract import and export logic into separate utility functions for better organization and maintainability.
This change simplifies the DataScreen component by delegating file handling responsibilities.

refactor(mobile): extract  import and export functionality for data setting

---

apps/desktop/src/renderer/src/modules/entry-column/atoms/index.ts

https://discord.com/channels/1243823539426033696/1265925366820765818/1348930877509337181

fix(desktop): use atomWithStorage for masonry column state

---

apps/mobile/src/atoms/settings/general.ts
apps/mobile/src/interfaces/settings/general.ts
apps/mobile/src/lib/native/index.ios.ts
apps/mobile/src/modules/entry-list/templates/EntryVideoItem.tsx
apps/mobile/src/modules/settings/routes/General.tsx

refactor(mobile): allow do not open links in app

---

.github/dependabot.yaml
packages/components/package.json
pnpm-lock.yaml

build: revert unist-util-visit-parents update

---

.github/workflows/build-eas.yml

ci: include lock file in path check

---

apps/mobile/src/modules/login/index.tsx

fix(mobile): allow scroll in login page

---

apps/mobile/src/modules/login/index.tsx

Revert "fix(mobile): allow scroll in login page"

---

.github/workflows/build-eas-development.yml
.github/workflows/build-eas.yml
apps/mobile/eas.json
pnpm-lock.yaml

This allows us to write non-native code in an environment without xcode

ci: add development build

---

apps/mobile/src/components/common/SubmitButton.tsx
apps/mobile/src/modules/login/email.tsx
apps/mobile/src/modules/login/index.tsx
apps/mobile/src/screens/(modal)/forget-password.tsx
apps/mobile/src/screens/(modal)/sign-up.tsx

fix(mobile): show validate message, support for small screen

---

apps/desktop/src/renderer/src/modules/entry-column/templates/list-item-template.tsx

The [previous](https://github.com/RSSNext/Follow/commit/90e56cf7f9c4849c7f99169107e7520ab65b673a) hyphen modification missed the description section of the article list.
#2846

fix(desktop): description section uses hyphen style

---

apps/mobile/src/components/ui/form/Select.tsx
apps/mobile/src/modules/settings/actions/components.tsx
apps/mobile/src/modules/settings/routes/EditCondition.tsx
apps/mobile/src/modules/settings/routes/EditRule.tsx

refactor(mobile): action condition layout and select

---

.github/workflows/build-eas-development.yml
.github/workflows/build-eas.yml
package.json
pnpm-lock.yaml
pnpm-workspace.yaml

build: update to pnpm 10

---

apps/desktop/src/renderer/src/modules/entry-column/templates/list-item-template.tsx
packages/components/src/utils/dayjs.ts
packages/utils/src/utils.ts

I found the format of `duration_in_seconds` is not correct here.
After:
https://github.com/user-attachments/assets/3df1ad70-e6d6-4b22-9183-dbb53cc04a37

fix: incorrect formatting of time duration

---

packages/utils/src/utils.ts

refactor: improve time formatting to support multiple formats

---

apps/mobile/src/modules/login/index.tsx
apps/mobile/src/screens/(modal)/sign-up.tsx

refactor(mobile): avoid multiple useScaleHeight call

---

apps/desktop/package.json
pnpm-lock.yaml

build: fix electron version

---

apps/desktop/changelog/next.md
apps/desktop/src/renderer/src/modules/timeline-column/FeedList.shared.tsx
apps/desktop/src/renderer/src/store/subscription/store.ts

fix: unable to update subscription information in time

---

apps/desktop/src/renderer/src/wdyr.ts

build: disable logging in react-scan by default

---

apps/mobile/src/modules/settings/routes/EditProfile.tsx
apps/mobile/src/screens/(stack)/(tabs)/subscriptions.tsx

Remove a redundant header from the Edit Profile modal and add a key prop to the SubscriptionList for improved rendering.

fix: add key prop to SubscriptionList

---

apps/desktop/src/renderer/src/hooks/biz/useSubscriptionActions.tsx
apps/desktop/src/renderer/src/modules/discover/feed-form.tsx
apps/desktop/src/renderer/src/modules/discover/import.tsx
apps/desktop/src/renderer/src/modules/discover/list-form.tsx
apps/desktop/src/renderer/src/modules/timeline-column/CategoryRenameContent.tsx
apps/desktop/src/renderer/src/modules/timeline-column/FeedList.shared.tsx
apps/desktop/src/renderer/src/queries/subscriptions.ts

refactor: always query all subscription list

---

apps/desktop/src/renderer/src/modules/discover/recommendations.tsx

fix: recommendations header has no background color

---

apps/desktop/src/main/src/index.ts

- https://github.com/Bekacru/better-call/pull/10

fix: do not decode cookie

---

apps/mobile/src/modules/entry-list/templates/EntryNormalItem.tsx
apps/mobile/src/modules/subscription/CategoryGrouped.tsx
apps/mobile/src/modules/subscription/SubscriptionLists.tsx
apps/mobile/src/modules/subscription/items/InboxItem.tsx
apps/mobile/src/modules/subscription/items/ListSubscriptionItem.tsx
apps/mobile/src/modules/subscription/items/SubscriptionItem.tsx

refactor(mobile): unify colors in dark and light modes

---

apps/mobile/src/components/layouts/tabbar/Tabbar.tsx

fix(mobile): ensure minimum padding at the bottom of the tab bar

---

apps/mobile/src/modules/screen/PageList.tsx
apps/mobile/src/modules/subscription/SubscriptionLists.tsx
apps/mobile/src/screens/(stack)/(tabs)/subscriptions.tsx

fix(mobile): category item border radius, background color

---

README.md

docs: link to CONTRIBUTING.md

---

apps/mobile/src/modules/entry-list/hooks.ts

fix(mobile): scroll to mark read not work

---

apps/mobile/src/components/ui/grouped/GroupedList.tsx

chore: fix type

---

apps/mobile/src/components/layouts/views/SafeNavigationScrollView.tsx
apps/mobile/src/modules/subscription/SubscriptionLists.tsx
apps/mobile/src/screens/(stack)/(tabs)/settings.tsx
apps/mobile/src/screens/(stack)/(tabs)/subscriptions.tsx

Fix FOL-1774
Introduce an active prop to the SubscriptionList component to ensure proper scrolling behavior in the subscription tab.

fix: scroll to top in subscription tab by adding active prop

---

.github/workflows/build-eas.yml

ci: restrict ipa build workflow to dev branch only

---

apps/desktop/src/renderer/src/modules/entry-column/item.tsx
apps/desktop/src/renderer/src/modules/profile/user-profile-modal.shared.tsx
apps/desktop/src/renderer/src/modules/shared/ViewSelectorRadioGroup.tsx

Resolve FOL-1719
Enhance the user interface by updating the follow button text and improving the EntryItemSkeleton component to dynamically handle the count of skeleton items. Additionally, add a skeleton loading state for entries in the ViewSelectorRadioGroup.

fix: improve skeleton loading states in feed preview

---

apps/desktop/locales/settings/en.json
apps/desktop/locales/settings/zh-CN.json
apps/desktop/src/renderer/src/modules/app-layout/feed-column/index.shared.tsx

Part of #3249
After:
https://github.com/user-attachments/assets/589afa8f-a014-4fad-a7ba-664ce4325815

feat(desktop): add email verification prompt and translation support

---

apps/mobile/src/modules/entry-list/templates/EntryNormalItem.tsx

fix(mobile): handle durationInSeconds format

---

.github/workflows/build.yml
apps/desktop/forge.config.cts
apps/desktop/scripts/update-windows-yml.ts

chore: signpath

---

.vscode/settings.json
apps/ssr/.env.example
apps/ssr/client/index.tsx

Adjust the editor settings in the configuration and introduce a new environment variable for the editor in the SSR application.
This change enhances flexibility by allowing the editor type to be set via environment variables.

chore: update editor configuration and environment variables

---

apps/desktop/src/main/src/lib/proxy.test.ts
apps/desktop/src/main/src/lib/proxy.ts
apps/desktop/src/renderer/src/modules/command/commands/integration.tsx

Enhance proxy configuration handling by adding support for SOCKS proxies and updating dependency management in command hooks to include necessary tokens and paths.

fix: proxy configuration and update command hook dependencies

---

apps/desktop/src/renderer/src/store/entry/hooks.ts
apps/desktop/src/renderer/src/store/entry/store.ts
apps/desktop/src/renderer/src/store/entry/types.ts
apps/mobile/package.json
packages/models/src/types.ts
packages/shared/package.json
packages/shared/src/hono.ts
pnpm-lock.yaml

- https://github.com/RSSNext/follow-server/pull/289

build: update better-auth

---

apps/desktop/locales/settings/en.json
apps/desktop/locales/settings/ja.json
apps/desktop/locales/settings/ko.json
apps/desktop/locales/settings/ru.json
apps/desktop/locales/settings/zh-CN.json
apps/desktop/locales/settings/zh-HK.json
apps/desktop/locales/settings/zh-TW.json
apps/desktop/src/renderer/src/modules/profile/account-management.tsx
apps/mobile/src/modules/settings/routes/Account.tsx
packages/shared/src/hono.ts

feat: enable allowDifferentEmails

---

apps/mobile/app.config.ts

fix(mobile): remove workaround for react-native-track-player

---

apps/desktop/src/renderer/src/modules/entry-content/components/EntryTitle.tsx

feat(desktop): update EntryTitle to handle localhost url

---

apps/desktop/src/renderer/src/components/ui/modal/stacked/modal.tsx

fix(desktop): modal close button cannot click

---

apps/desktop/src/renderer/src/modules/entry-column/templates/list-item-template.tsx
apps/desktop/src/renderer/src/modules/entry-content/components/EntryTitle.tsx
apps/desktop/src/renderer/src/modules/renderer/components/TimeStamp.tsx
apps/mobile/src/database/schemas/types.ts
apps/mobile/src/modules/entry-list/templates/EntryNormalItem.tsx
packages/shared/src/hono.ts
packages/utils/src/utils.ts

https://github.com/RSSNext/follow-server/commit/8491c18bff3d80a258d192e2aa33e893b8f58247

chore: fix durationInSeconds type

---

apps/desktop/src/renderer/src/modules/entry-column/Items/social-media-item.tsx

If there is not action, it will display a white dot.

fix: ensure ActionBar only displays when entryActions are available

---

apps/mobile/changelog/next.md
apps/mobile/src/modules/context-menu/feeds.tsx
apps/mobile/src/modules/entry-list/EntryListContentArticle.tsx
apps/mobile/src/modules/entry-list/EntryListContentPicture.tsx
apps/mobile/src/modules/entry-list/EntryListContentSocial.tsx
apps/mobile/src/modules/entry-list/EntryListContentVideo.tsx
apps/mobile/src/modules/entry-list/EntryListSelector.tsx
apps/mobile/src/modules/screen/TimelineSelectorProvider.tsx
apps/mobile/src/screens/(stack)/feeds/[feedId]/index.tsx
apps/mobile/src/store/entry/hooks.ts

fix(mobile): share feed button

---

locales/common/zh-CN.json

feat: add i18n with Chinese

---

apps/mobile/src/lib/dialog.tsx
apps/mobile/src/modules/dialogs/MarkAllAsReadDialog.tsx
apps/mobile/src/modules/screen/atoms.ts
apps/mobile/src/screens/(stack)/(tabs)/subscriptions.tsx
apps/mobile/src/screens/(stack)/feeds/[feedId]/index.tsx

fix(mobile): mark as read payload for feed list

---

apps/desktop/src/renderer/src/modules/ai/ai-daily/daily.tsx

Add internationalization for the date in the tooltip of the daily summary.
Before:
After:

feat(desktop): add locale for daily report title

---

apps/desktop/src/renderer/src/modules/discover/form.tsx
locales/app/zh-CN.json

fix(desktop): adjust layout and styling in SearchCard component

---

apps/mobile/scripts/with-follow-assets.js
apps/mobile/src/components/native/webview/constants.ts
apps/mobile/src/components/native/webview/index.android.ts
apps/mobile/src/components/native/webview/injected-js.ts
apps/mobile/src/components/native/webview/native-webview.android.tsx

feat(mobile): implement webview in android

---

apps/desktop/src/main/src/index.ts

Fix https://github.com/RSSNext/Folo/issues/3312
This pull request includes changes to the `bootstrap` function in `index.ts` and the `createBuildSafeHeaders` function in `headers.ts` to handle HTTP methods more effectively and improve header safety.

fix: unexpected CORS error

---

apps/desktop/src/renderer/src/components/ui/button/CopyButton.tsx
apps/desktop/src/renderer/src/components/ui/button/base.tsx
apps/desktop/src/renderer/src/components/ui/code-highlighter/constants/index.tsx
apps/desktop/src/renderer/src/components/ui/code-highlighter/shiki/Shiki.tsx
apps/desktop/src/renderer/src/components/ui/code-highlighter/shiki/hooks.ts
apps/desktop/src/renderer/src/modules/rsshub/add-modal-content.tsx

| Before | After |
| ---- | ---- |
| <img src="https://github.com/user-attachments/assets/bb642c89-d276-48ad-8831-f37d0a123e81" width="300" /> |<img src="https://github.com/user-attachments/assets/7ee555db-db71-49cd-909d-9c60280c5250" width="300" /> |
| <img src="https://github.com/user-attachments/assets/55d796eb-8dbe-44e0-8a97-2ca1d0c00e84" width="300" /> | <img src="https://github.com/user-attachments/assets/6b8cbe03-6d08-4f24-88a3-b9b76fb94db9" width="300" /> |
| |<img src="https://github.com/user-attachments/assets/3c7133cd-abca-4ada-89e7-96cb04643e43" width="300" /> |
|  | <img src="https://github.com/user-attachments/assets/d49ee0f8-3ff7-432f-8f4d-2e7e45388457" width="300" /> |

refactor(desktop): improve shiki highlight component

---

apps/desktop/src/renderer/src/hooks/biz/useEntryActions.tsx
apps/mobile/src/morph/hono.ts
packages/shared/src/hono.ts

- https://github.com/RSSNext/follow-server/pull/305

refactor: split readability table

---

apps/desktop/bump.config.ts
apps/desktop/package.json
apps/mobile/bump.config.ts
apps/mobile/package.json

Signed-off-by: Innei <tukon479@gmail.com>

chore: publish config

---

apps/mobile/app.config.ts
apps/mobile/package.json
pnpm-lock.yaml

fix(mobile): add react-native-edge-to-edge for status bar handling on Android

---

apps/desktop/src/renderer/src/hooks/biz/useEntryActions.tsx
apps/desktop/src/renderer/src/hooks/common/useFeedSafeUrl.ts
apps/desktop/src/renderer/src/modules/command/commands/entry.tsx
apps/desktop/src/renderer/src/modules/command/commands/types.ts
apps/desktop/src/renderer/src/modules/discover/form.tsx
apps/desktop/src/renderer/src/modules/entry-content/components/EntryTitle.tsx
apps/desktop/src/renderer/src/modules/entry-content/index.electron.tsx
packages/utils/src/utils.ts

Close: #3494 
https://github.com/user-attachments/assets/8ed581fb-cdeb-4089-b8c8-c3278fdb4138

feat(desktop): resolve url with site url to make sure url is valid

---

apps/mobile/src/components/ui/pressable/ItemPressable.tsx

Fix the context menu to show even when a short press is made on the entry items

fix(mobile): remove GestureDetector on ItemPressable

---

apps/desktop/src/main/src/updater/configs.ts

Disable updater for process from custom location.
Disable updater for process from custom location.
.
.
#1310
.
.

feat: disable core updater for process from custom location

---

apps/mobile/src/components/layouts/header/NavigationHeader.tsx
apps/mobile/src/lib/navigation/StackNavigation.tsx
apps/mobile/src/modules/login/index.tsx
apps/mobile/src/screens/(modal)/ForgetPasswordScreen.tsx
apps/mobile/src/screens/(modal)/SignUpScreen.tsx
apps/mobile/src/screens/(modal)/TwoFactorAuthScreen.tsx

fix: normalize safe area insets in android

---

apps/desktop/src/renderer/src/modules/trending/index.tsx
locales/app/en.json
locales/app/zh-CN.json

feat(desktop): improve ux in trending

---

apps/mobile/src/components/common/RotateableLoading.tsx
apps/mobile/src/components/ui/loading/PlatformActivityIndicator.tsx

fix(mobile): loading style in android

---

apps/mobile/src/store/entry/store.ts

Ensure consistent casing for HTTP methods in the mobile app's entry store.

fix(mobile): standardize HTTP method casing

---

apps/mobile/src/components/ui/toast/CenteredToast.tsx
apps/mobile/src/components/ui/toast/manager.tsx
apps/mobile/src/components/ui/toast/types.ts
apps/mobile/src/lib/toast.tsx

Ensure the default duration is applied when showing toast messages, handle potential undefined references

fix: toast message handling on android

---

apps/desktop/src/renderer/src/modules/discover/form.tsx

https://github.com/user-attachments/assets/55d1cda7-847f-49ac-a7db-d77a534066cc

feat(desktop): add clear results and reset keyword field

---

apps/desktop/layer/renderer/src/modules/discover/DiscoverFeedForm.tsx

Once the preview button is clicked, the empty input field fails to restore focus.
After:
https://github.com/user-attachments/assets/1668a8de-799d-43ba-b2ff-c14f2d341549

fix(desktop):  discover feed form can't handle failed validation

---

apps/desktop/layer/renderer/src/modules/entry-content/AISummary.tsx

- Before:
- After:
closes #3639

feat(AI Summary): add support for render Markdown in AI Summary

---

apps/desktop/layer/renderer/src/modules/discover/feed-card.tsx
apps/desktop/layer/renderer/src/modules/discover/recommendations.tsx
locales/app/zh-CN.json

Some minor improvements.
1. Add i18n
2. Fix eslint error

chore(desktop): minor improvement for discover page

---

apps/desktop/layer/renderer/src/modules/timeline-column/FeedList.shared.tsx

fix(desktop): wrong order and icon in sort list header

---

apps/mobile/app.config.ts
apps/mobile/package.json
apps/mobile/src/initialize/background.ts
apps/mobile/src/initialize/index.ts
pnpm-lock.yaml

refactor: migrate to expo-background-task

---

.github/workflows/build-ios-development.yml
apps/mobile/app.config.ts

ci: macos-15 and xcode 16.3

---

apps/mobile/src/lib/navigation/bottom-tab/TabScreen.tsx

fix: add native view wrappers for TabBar components

---

README.md

Due to a few things, I've been assisting timochan with packaging. I've merged the original `follow-appimage` into the new `folo-appimage` and fixed the previous issues.
As a result, Arch users can use this [package](https://aur.archlinux.org/packages/folo-appimage).

docs(README): update Arch package name and maintainers

---

apps/mobile/src/modules/screen/atoms.ts
apps/mobile/src/modules/subscription/CategoryGrouped.tsx
apps/mobile/src/modules/subscription/SubscriptionLists.tsx
apps/mobile/src/modules/subscription/UnGroupedList.tsx
apps/mobile/src/modules/subscription/items/SubscriptionItem.tsx
apps/mobile/src/modules/subscription/items/types.tsx

fix(mobile): separator style, clean useless code

---

apps/desktop/layer/renderer/src/hooks/biz/useSubscriptionActions.tsx
apps/desktop/layer/renderer/src/modules/entry-column/components/mark-all-button.tsx

fix(desktop): update keyboard shortcut styling for undo action

---

.github/workflows/build-desktop.yml
package.json

fix: escape quotes in build script

---

apps/desktop/layer/renderer/src/modules/discover/DiscoverFeedForm.tsx
apps/desktop/layer/renderer/src/modules/discover/DiscoverTransform.tsx

Close: #3752
https://github.com/user-attachments/assets/fd583837-ae5b-435b-8a77-003278baaa8a

fix(desktop): add overflow-scroll for content visibility

---

apps/desktop/layer/renderer/src/modules/profile/user-profile-modal.shared.tsx

The subscription list failed to render due to userInfo being null.

fix(desktop): use profile query with userInfo fallback in Avatar

---

apps/mobile/src/components/layouts/views/SafeNavigationScrollView.tsx
apps/mobile/src/modules/context-menu/feeds.tsx
apps/mobile/src/modules/entry-content/use-pull-up-to-next.tsx
apps/mobile/src/modules/entry-list/EntryListContentArticle.tsx
apps/mobile/src/modules/entry-list/EntryListContentSocial.tsx
apps/mobile/src/modules/entry-list/templates/EntryNormalItem.tsx
apps/mobile/src/modules/entry-list/templates/EntrySocialItem.tsx
apps/mobile/src/modules/entry-list/types.ts
apps/mobile/src/screens/(stack)/entries/[entryId]/EntryDetailScreen.tsx

Refactor to utilize `EntryExtraData` for improved state management. Add support for an `onScroll` callback in `SafeNavigationScrollView`. Implement pull-up-to-next functionality in `EntryDetailScreen` to facilitate seamless navigation between entries.

feat: implement pull up to next functionality

---

apps/mobile/src/components/layouts/views/SafeNavigationScrollView.tsx
apps/mobile/src/modules/entry-content/use-pull-up-to-next.tsx
apps/mobile/src/screens/(stack)/entries/[entryId]/EntryDetailScreen.tsx
locales/mobile/default/en.json
locales/mobile/default/zh-CN.json

Implement the `EntryPullUpToNext` component to improve navigation experience and integrate it into `EntryDetailScreen`.

feat: add entry pull up and release ui

---

packages/internal/components/src/ui/avatar-group/index.tsx

fix: prevent hydration error by set TooltipTrigger to use asChild prop

---

apps/desktop/layer/renderer/src/lib/parse-html.ts
packages/internal/components/src/ui/markdown/parse-html.ts

Improve the video component to handle source elements and add support for preview images. Fix the parsing function to include source attributes for video elements.

fix: enhance video component

---

apps/mobile/src/modules/settings/routes/Account.tsx

fix(mobile): email warp (#3791)

---

apps/mobile/src/components/ui/video/VideoPlayer.tsx
apps/mobile/src/modules/entry-list/templates/EntryNormalItem.tsx

Introduce video support in the EntryNormalItem component and improve media handling by allowing both audio and video attachments. Update the VideoPlayer component to correct reference names and ensure proper functionality.

feat: add video support in EntryNormalItem

---

plugins/eslint/eslint-check-i18n-json.js
plugins/eslint/eslint-recursive-sort.js
plugins/utils.js

Before:
https://github.com/user-attachments/assets/c865d926-1a50-4a60-b2fe-0bc1e634a9b6
After:
https://github.com/user-attachments/assets/88201740-69d5-40c7-9b05-3da4ab870dc8

feat: integrate cleanJsonText function for json parsing

---

apps/desktop/layer/renderer/src/modules/command/shortcuts/SettingShortcuts.tsx
locales/shortcuts/en.json
locales/shortcuts/zh-CN.json

https://github.com/user-attachments/assets/4a82616f-7418-48d0-9759-3921182b6f3f

feat(desktop): add i18n for shortcut settings and improve style

---

apps/desktop/layer/renderer/src/pages/(main)/(layer)/(subview)/rsshub/index.tsx

fix(rsshub): update label text from 'Follow' to 'Folo'

---

apps/mobile/src/modules/screen/PagerList.ios.tsx

Correct the assignment of initialPageIndex to ensure it reflects the active view index properly.

fix: pager flicker

---

CONTRIBUTING.md

Forgetting to execute `cp .env.example .env` will cause the iOS app to fail to run, throwing the error:
```bash
ERROR  [runtime not ready]: Error: No modules in context, js engine: hermes
```

docs: update mobile app development steps in contributing guide

---

apps/desktop/layer/renderer/src/modules/auth/LoginModalContent.tsx
apps/ssr/client/modules/login/index.tsx
apps/ssr/client/pages/(login)/register.tsx

**The icons on the form, login, register, etc. pages were not switching automatically with the theme, I fixed it!**
**Bug Video**
<video src="https://github.com/user-attachments/assets/3892abcb-1e5a-4b20-9c72-534657073f9b" width="50%" controls></video>
**After Fix**
<video src="https://github.com/user-attachments/assets/1667d396-9d1e-42f2-92a1-1700dd26fb1a" width="50%" controls></video>

fix: icon can't follow theme switch correctly

---

apps/desktop/layer/renderer/src/modules/subscription-column/FeedCategory.tsx

feat: don't show the group entries when click the > button on desktop

---

apps/mobile/native/example/src/components/Pager.tsx
apps/mobile/native/ios/Modules/PagerView/EnhancePagerController.swift
apps/mobile/native/ios/Modules/PagerView/EnhancePagerViewModule.swift
apps/mobile/src/components/native/PagerView/index.tsx
apps/mobile/src/components/native/PagerView/specs.ts
apps/mobile/src/modules/screen/PagerList.ios.tsx
apps/mobile/src/modules/screen/PagerList.tsx
apps/mobile/src/modules/screen/TimelineViewSelector.tsx
apps/mobile/src/modules/screen/atoms.ts
apps/mobile/src/providers/index.tsx

Improve user interaction by adding a position parameter to the onScroll event in PagerView for iOS, and integrate drag progress management in TimelineViewSelector. This includes animated transitions and a new context provider for drag state.

feat: enhance drag interactions in TimelineSelector

---

locales/settings/en.json
locales/settings/ja.json
locales/settings/zh-CN.json
locales/settings/zh-TW.json
packages/internal/models/src/types.ts
packages/internal/store/src/action/constant.ts

feat: add filter video length action

---

apps/desktop/configs/vite.electron-render.config.ts
apps/desktop/vite.config.ts
apps/ssr/vite.config.mts

As i mentioned in #3978 , the latest code con't run proper in Windows operating system, after i use Git bisect found it was caused by [this commit](https://github.com/RSSNext/Folo/commit/1d83313872f36473c9828b59d015b6367c13bf2b), it introduces `vite-plugin-route-builder`, but the config path of this plugin is not relative path， it use absolute path by using resolve method, it will cause the code can't run proper in Windows like this:
```powershell
@follow/web:dev: Build type: Web
@follow/web:dev: [route-builder-v2] Found 0 page files
@follow/web:dev: [route-builder-v2] Generated routes: C:\code\clone\Folo\apps\desktop\layer\renderer\src\generated-routes.ts
@follow/web:dev: 12:17:04 [vite] (client) Re-optimizing dependencies because vite config has changed
@follow/web:dev: TypeError: …
```

fix: use relative path in 'vite-plugin-route-builder' config

---

apps/desktop/layer/renderer/src/modules/app-layout/subview/SubviewLayout.tsx
apps/desktop/layer/renderer/src/modules/trending/index.tsx
apps/desktop/layer/renderer/src/pages/(main)/(layer)/(subview)/discover/category/[category].tsx
apps/desktop/layer/renderer/src/pages/(main)/(layer)/(subview)/discover/index.tsx
packages/internal/components/src/ui/scroll-area/ScrollArea.tsx
packages/internal/components/src/ui/scroll-area/ctx.ts
packages/internal/components/src/ui/scroll-area/hooks.ts

https://github.com/user-attachments/assets/5b109c11-ee11-4fcc-952b-c73da6d78bdc
https://github.com/user-attachments/assets/6bb772d8-0985-4d62-aee3-ddf1a1ed4eaf

feat: enhance scroll state management

---

apps/desktop/layer/renderer/src/modules/entry-column/templates/list-item-template.tsx

|  | 🍎 | 🍎 |
| --- | --- | --- |
| ![CleanShot 2025-06-25 at 12 13 02](https://github.com/user-attachments/assets/75b2cd9e-42bf-4d96-bfa8-5ca786c54eb7) | ![wecom-temp-206162-74e51a7f29e8be0625dcf2d3175a7ac2](https://github.com/user-attachments/assets/d1bb55aa-9cda-4850-b922-037824602384) | ![wecom-temp-210418-88fb6099f8a2f0b75f34e0f883b030d8](https://github.com/user-attachments/assets/cc3fbd8e-8ad7-4d4c-bfc8-34ad7dbe854c)|

feat(desktop): enhance podcast duration display

---

apps/mobile/src/components/ui/form/Select.android.tsx
apps/mobile/src/components/ui/modal/BottomModal.tsx

Introduce a BottomModal component for animated modal functionality and implement a Select component that utilizes the BottomModal for option selection on Android.

feat: add BottomModal and Select components for Android

---

apps/desktop/layer/renderer/src/main.tsx
apps/desktop/layer/renderer/src/modules/discover/FeedForm.tsx
apps/desktop/layer/renderer/src/modules/discover/ListForm.tsx
apps/desktop/layer/renderer/src/modules/entry-column/hooks/useEntriesByView.ts
apps/desktop/layer/renderer/src/modules/subscription-column/FeedCategory.tsx
apps/desktop/layer/renderer/src/queries/entries.ts
apps/desktop/layer/renderer/src/queries/feed.ts
apps/mobile/src/main.tsx
apps/mobile/src/modules/context-menu/feeds.tsx
apps/mobile/src/modules/screen/atoms.ts
packages/internal/database/src/services/collection.ts
packages/internal/store/src/collection/store.ts
packages/internal/store/src/context.ts
packages/internal/store/src/entry/hooks.ts
packages/internal/store/src/entry/store.ts
packages/internal/store/src/entry/types.ts
packages/internal/store/src/morph/hono.ts
packages/internal/store/src/subscription/store.ts

fix: collection is not up to date

---

package.json
pnpm-workspace.yaml

Reference:
- https://github.com/vitejs/vite/blob/main/pnpm-workspace.yaml#L16
- https://github.com/orgs/pnpm/discussions/9037

chore: move pnpm setting to pnpm-workspace

---

apps/desktop/layer/renderer/src/modules/entry-column/components/FooterMarkItem.tsx
apps/desktop/layer/renderer/src/modules/entry-column/index.tsx

This bug from Discord user group.
The `Mark above as read` button should not visible in Starred view.
|Before|After|
|----|----|
|![before](https://github.com/user-attachments/assets/95fa9ac3-7275-4203-916a-1b7c7e9cb5df)|![after](https://github.com/user-attachments/assets/b8b6e9b2-1f97-4e9d-b592-79a0e5c6317a)|

fix: don't show 'Mark above as read' button in Starred view

---

vercel.json

feat: use multi env for app.follow.is and app.folo.is

---

apps/mobile/src/initialize/index.ts
apps/mobile/src/initialize/player.ts
apps/mobile/src/lib/player.ts

Fix https://github.com/RSSNext/Folo/issues/3803
Ensure the player initializes correctly by implementing a retry mechanism and handling background execution errors. Add a check for player registration to prevent errors during playback.

fix: player initialization issues

---

apps/mobile/src/components/ui/video/PlayerAction.tsx
apps/mobile/src/components/ui/video/VideoPlayer.tsx
apps/mobile/src/lib/player.ts
apps/mobile/src/modules/context-menu/feeds.tsx
apps/mobile/src/modules/entry-list/EntryListContentArticle.tsx
apps/mobile/src/modules/entry-list/EntryListContentSocial.tsx
apps/mobile/src/modules/entry-list/templates/EntryNormalItem.tsx
apps/mobile/src/modules/entry-list/types.ts

Enhance audio playback control by simplifying state management and enabling audio pause. Remove unnecessary properties and streamline the handling of audio states across components.

refactor: simplify audio state handling

---

packages/internal/store/src/subscription/store.ts

<table>
<tr>
<td>
After
<td>
Before
<tr>
<td>
https://github.com/user-attachments/assets/cdec0663-36ad-4a89-b6a8-07633a03575e
<td>
https://github.com/user-attachments/assets/ec52f7cb-eaf1-49b9-87d5-a3c6476208ab
</table>

fix(desktop): feed drag back to original category issue

---

apps/desktop/layer/renderer/src/push-notification.ts

fix(desktop): load firebase app

---

apps/ssr/client/pages/(main)/share/users/[id]/index.tsx

`https://app.folo.is/share/users/innei`
neet two click to collapse category.

fix: neet two click to collapse category

---

apps/desktop/layer/renderer/src/components/ui/crop/AvatarUploadModal.tsx
apps/desktop/layer/renderer/src/modules/discover/DiscoverImport.tsx
packages/internal/components/src/ui/drop-zone/index.tsx

Fix: https://discord.com/channels/1243823539426033696/1265925366820765818/1404283528329564290

refactor(desktop): enhance drop-zone component flexibility

---

apps/desktop/layer/renderer/src/modules/settings/tabs/lists/modals.tsx
packages/internal/store/src/feed/getter.ts

fix(desktop): feed title not showing in list pick

---

apps/desktop/layer/renderer/src/modules/modal/hooks/useConfirmUnsubscribeSubscriptionModal.tsx
apps/desktop/layer/renderer/src/modules/settings/tabs/feeds.tsx

<table>
<tr>
<td>
Before
<td>
After
<tr>
<td>
https://github.com/user-attachments/assets/66544864-67f5-4175-86bd-7f90a2cffe76
<td>
https://github.com/user-attachments/assets/7927b3c8-2c43-452c-a6d5-7ba33ce7801f
</table>

fix(desktop): clear selected subscriptions after deleting

---

README.md

chore: remove the power section in readme

---

apps/desktop/layer/renderer/src/modules/ai-chat-session/index.ts
apps/desktop/layer/renderer/src/modules/ai-chat-session/query.ts
apps/desktop/layer/renderer/src/modules/ai-chat-session/service.ts
apps/desktop/layer/renderer/src/modules/ai-chat/components/layouts/AIChatRoot.tsx
apps/desktop/layer/renderer/src/modules/ai-chat/components/layouts/ChatHeader.tsx
apps/desktop/layer/renderer/src/modules/ai-chat/components/layouts/ChatSessionDropdown.tsx
apps/desktop/layer/renderer/src/modules/ai-chat/components/layouts/TaskReportDropdown.tsx
apps/desktop/layer/renderer/src/modules/ai-chat/services/index.ts
apps/desktop/layer/renderer/src/modules/ai-chat/store/chat-core/chat-actions.ts
apps/desktop/layer/renderer/src/modules/ai-task/components/ai-item-actions.tsx
apps/desktop/layer/renderer/src/modules/ai-task/components/ai-task-modal.tsx
apps/desktop/layer/renderer/src/modules/ai-task/components/task-item.tsx
apps/desktop/layer/renderer/src/modules/ai-task/components/task-list.tsx
apps/desktop/layer/renderer/src/modules/entry-column/AIEntryLayout.tsx
locales/ai/en.json
locales/ai/ja.json
locales/ai/zh-CN.json

Introduce queries and a dropdown component for managing AI chat sessions, enhancing user interaction with chat sessions. The new functionality allows users to list, select, and delete chat sessions seamlessly.

feat(ai): add AI chat session management features

---

pnpm-lock.yaml
pnpm-workspace.yaml

chore: update @follow-app/client-sdk to 0.3.51
